// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: search.proto

package searchservice

import (
	"context"

	"polaris-io/backend/app/search/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteFileIndexReq  = pb.DeleteFileIndexReq
	DeleteFileIndexResp = pb.DeleteFileIndexResp
	FileItem            = pb.FileItem
	GetUserStatsReq     = pb.GetUserStatsReq
	GetUserStatsResp    = pb.GetUserStatsResp
	IndexFileReq        = pb.IndexFileReq
	IndexFileResp       = pb.IndexFileResp
	SearchFilesReq      = pb.SearchFilesReq
	SearchFilesResp     = pb.SearchFilesResp
	UpdateFileIndexReq  = pb.UpdateFileIndexReq
	UpdateFileIndexResp = pb.UpdateFileIndexResp

	SearchService interface {
		// -------- 搜索接口 --------
		SearchFiles(ctx context.Context, in *SearchFilesReq, opts ...grpc.CallOption) (*SearchFilesResp, error)
		// 获取用户文件统计
		GetUserStats(ctx context.Context, in *GetUserStatsReq, opts ...grpc.CallOption) (*GetUserStatsResp, error)
		// -------- 索引管理（内部调用） --------
		IndexFile(ctx context.Context, in *IndexFileReq, opts ...grpc.CallOption) (*IndexFileResp, error)
		// 更新文件索引
		UpdateFileIndex(ctx context.Context, in *UpdateFileIndexReq, opts ...grpc.CallOption) (*UpdateFileIndexResp, error)
		// 删除文件索引
		DeleteFileIndex(ctx context.Context, in *DeleteFileIndexReq, opts ...grpc.CallOption) (*DeleteFileIndexResp, error)
	}

	defaultSearchService struct {
		cli zrpc.Client
	}
)

func NewSearchService(cli zrpc.Client) SearchService {
	return &defaultSearchService{
		cli: cli,
	}
}

// -------- 搜索接口 --------
func (m *defaultSearchService) SearchFiles(ctx context.Context, in *SearchFilesReq, opts ...grpc.CallOption) (*SearchFilesResp, error) {
	client := pb.NewSearchServiceClient(m.cli.Conn())
	return client.SearchFiles(ctx, in, opts...)
}

// 获取用户文件统计
func (m *defaultSearchService) GetUserStats(ctx context.Context, in *GetUserStatsReq, opts ...grpc.CallOption) (*GetUserStatsResp, error) {
	client := pb.NewSearchServiceClient(m.cli.Conn())
	return client.GetUserStats(ctx, in, opts...)
}

// -------- 索引管理（内部调用） --------
func (m *defaultSearchService) IndexFile(ctx context.Context, in *IndexFileReq, opts ...grpc.CallOption) (*IndexFileResp, error) {
	client := pb.NewSearchServiceClient(m.cli.Conn())
	return client.IndexFile(ctx, in, opts...)
}

// 更新文件索引
func (m *defaultSearchService) UpdateFileIndex(ctx context.Context, in *UpdateFileIndexReq, opts ...grpc.CallOption) (*UpdateFileIndexResp, error) {
	client := pb.NewSearchServiceClient(m.cli.Conn())
	return client.UpdateFileIndex(ctx, in, opts...)
}

// 删除文件索引
func (m *defaultSearchService) DeleteFileIndex(ctx context.Context, in *DeleteFileIndexReq, opts ...grpc.CallOption) (*DeleteFileIndexResp, error) {
	client := pb.NewSearchServiceClient(m.cli.Conn())
	return client.DeleteFileIndex(ctx, in, opts...)
}
