// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"polaris-io/backend/pkg/globalkey"
)

var (
	shareFieldNames          = builder.RawFieldNames(&Share{})
	shareRows                = strings.Join(shareFieldNames, ",")
	shareRowsExpectAutoSet   = strings.Join(stringx.Remove(shareFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	shareRowsWithPlaceHolder = strings.Join(stringx.Remove(shareFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	shareModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Share) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Share, error)
		Update(ctx context.Context, session sqlx.Session, data *Share) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Share) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *Share) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Share, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Share, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Share, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Share, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Share, error)
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultShareModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Share struct {
		Id                 uint64    `db:"id"`
		Identity           string    `db:"identity"`            // 分享唯一标识
		UserId             uint64    `db:"user_id"`             // 分享者ID
		RepositoryIdentity string    `db:"repository_identity"` // 关联文件Identity
		Code               string    `db:"code"`                // 提取码
		ClickNum           uint64    `db:"click_num"`           // 点击次数
		ExpiredTime        uint64    `db:"expired_time"`        // 失效时间(0永久)
		Status             int64     `db:"status"`              // 业务状态 0:正常 1:已封禁
		Version            uint64    `db:"version"`             // 乐观锁版本号
		DelState           int64     `db:"del_state"`           // 删除状态 0:正常 1:已取消(软删)
		DeleteTime         uint64    `db:"delete_time"`         // 删除时间戳(0:未删 >0:已删)
		CreateTime         time.Time `db:"create_time"`
		UpdateTime         time.Time `db:"update_time"`
	}
)

func newShareModel(conn sqlx.SqlConn) *defaultShareModel {
	return &defaultShareModel{
		conn:  conn,
		table: "`share`",
	}
}

func (m *defaultShareModel) Insert(ctx context.Context, session sqlx.Session, data *Share) (sql.Result, error) {
	data.DeleteTime = 0
	data.DelState = globalkey.DelStateNo

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, shareRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Identity, data.UserId, data.RepositoryIdentity, data.Code, data.ClickNum, data.ExpiredTime, data.Status, data.Version, data.DelState, data.DeleteTime)
	}
	return m.conn.ExecCtx(ctx, query, data.Identity, data.UserId, data.RepositoryIdentity, data.Code, data.ClickNum, data.ExpiredTime, data.Status, data.Version, data.DelState, data.DeleteTime)
}

func (m *defaultShareModel) FindOne(ctx context.Context, id uint64) (*Share, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  and del_state = ? limit 1", shareRows, m.table)
	var resp Share
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, globalkey.DelStateNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShareModel) Update(ctx context.Context, session sqlx.Session, data *Share) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shareRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Identity, data.UserId, data.RepositoryIdentity, data.Code, data.ClickNum, data.ExpiredTime, data.Status, data.Version, data.DelState, data.DeleteTime, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Identity, data.UserId, data.RepositoryIdentity, data.Code, data.ClickNum, data.ExpiredTime, data.Status, data.Version, data.DelState, data.DeleteTime, data.Id)
}

func (m *defaultShareModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Share) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, shareRowsWithPlaceHolder)
	if session != nil {
		sqlResult, err = session.ExecCtx(ctx, query, data.Identity, data.UserId, data.RepositoryIdentity, data.Code, data.ClickNum, data.ExpiredTime, data.Status, data.Version, data.DelState, data.DeleteTime, data.Id, oldVersion)
	} else {
		sqlResult, err = m.conn.ExecCtx(ctx, query, data.Identity, data.UserId, data.RepositoryIdentity, data.Code, data.ClickNum, data.ExpiredTime, data.Status, data.Version, data.DelState, data.DeleteTime, data.Id, oldVersion)
	}

	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultShareModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *Share) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = uint64(time.Now().Unix())
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ShareModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultShareModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultShareModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultShareModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*Share, error) {

	builder = builder.Columns(shareRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Share

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultShareModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Share, error) {

	builder = builder.Columns(shareRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Share

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultShareModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Share, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(shareRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*Share

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultShareModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Share, error) {

	builder = builder.Columns(shareRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Share

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultShareModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Share, error) {

	builder = builder.Columns(shareRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Share

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultShareModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultShareModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultShareModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShareModel) tableName() string {
	return m.table
}
