// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: search.proto

package server

import (
	"context"

	"polaris-io/backend/app/search/cmd/rpc/internal/logic/searchservice"
	"polaris-io/backend/app/search/cmd/rpc/internal/svc"
	"polaris-io/backend/app/search/cmd/rpc/pb"
)

type SearchServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSearchServiceServer
}

func NewSearchServiceServer(svcCtx *svc.ServiceContext) *SearchServiceServer {
	return &SearchServiceServer{
		svcCtx: svcCtx,
	}
}

// -------- 搜索接口 --------
func (s *SearchServiceServer) SearchFiles(ctx context.Context, in *pb.SearchFilesReq) (*pb.SearchFilesResp, error) {
	l := searchservicelogic.NewSearchFilesLogic(ctx, s.svcCtx)
	return l.SearchFiles(in)
}

// 获取用户文件统计
func (s *SearchServiceServer) GetUserStats(ctx context.Context, in *pb.GetUserStatsReq) (*pb.GetUserStatsResp, error) {
	l := searchservicelogic.NewGetUserStatsLogic(ctx, s.svcCtx)
	return l.GetUserStats(in)
}

// -------- 索引管理（内部调用） --------
func (s *SearchServiceServer) IndexFile(ctx context.Context, in *pb.IndexFileReq) (*pb.IndexFileResp, error) {
	l := searchservicelogic.NewIndexFileLogic(ctx, s.svcCtx)
	return l.IndexFile(in)
}

// 更新文件索引
func (s *SearchServiceServer) UpdateFileIndex(ctx context.Context, in *pb.UpdateFileIndexReq) (*pb.UpdateFileIndexResp, error) {
	l := searchservicelogic.NewUpdateFileIndexLogic(ctx, s.svcCtx)
	return l.UpdateFileIndex(in)
}

// 删除文件索引
func (s *SearchServiceServer) DeleteFileIndex(ctx context.Context, in *pb.DeleteFileIndexReq) (*pb.DeleteFileIndexResp, error) {
	l := searchservicelogic.NewDeleteFileIndexLogic(ctx, s.svcCtx)
	return l.DeleteFileIndex(in)
}
