// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type FileItem struct {
	Id         string `json:"id"`         // 文件 identity
	FileId     int64  `json:"fileId"`     // MySQL file_id
	Name       string `json:"name"`       // 文件名
	Ext        string `json:"ext"`        // 扩展名
	Size       uint64 `json:"size"`       // 文件大小
	IsDir      bool   `json:"isDir"`      // 是否为文件夹
	ParentId   int64  `json:"parentId"`   // 父目录ID
	CreateTime int64  `json:"createTime"` // 创建时间
	UpdateTime int64  `json:"updateTime"` // 更新时间
}

type GetUserStatsReq struct {
}

type GetUserStatsResp struct {
	TotalFiles   int64 `json:"totalFiles"`   // 文件总数
	TotalFolders int64 `json:"totalFolders"` // 文件夹总数
}

type SearchFilesReq struct {
	Keyword  string   `form:"keyword,optional"`    // 搜索关键词
	Ext      []string `form:"ext,optional"`        // 文件扩展名过滤
	IsDir    *bool    `form:"isDir,optional"`      // 是否只搜索文件夹
	MinSize  *uint64  `form:"minSize,optional"`    // 最小文件大小
	MaxSize  *uint64  `form:"maxSize,optional"`    // 最大文件大小
	Page     int      `form:"page,default=1"`      // 页码
	PageSize int      `form:"pageSize,default=20"` // 每页数量
	SortBy   string   `form:"sortBy,optional"`     // 排序字段: name, size, create_time, update_time
	SortDesc bool     `form:"sortDesc,optional"`   // 是否降序
}

type SearchFilesResp struct {
	Total int64      `json:"total"` // 总数
	List  []FileItem `json:"list"`  // 文件列表
}
