// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: app/file/cmd/rpc/pb/file.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileService_CheckInstantUpload_FullMethodName    = "/pb.FileService/CheckInstantUpload"
	FileService_GetPresignedUploadUrl_FullMethodName = "/pb.FileService/GetPresignedUploadUrl"
	FileService_CreateFile_FullMethodName            = "/pb.FileService/CreateFile"
	FileService_CreateFolder_FullMethodName          = "/pb.FileService/CreateFolder"
	FileService_GetFileInfo_FullMethodName           = "/pb.FileService/GetFileInfo"
	FileService_GetFilesByIds_FullMethodName         = "/pb.FileService/GetFilesByIds"
	FileService_CheckFileExists_FullMethodName       = "/pb.FileService/CheckFileExists"
	FileService_ListFiles_FullMethodName             = "/pb.FileService/ListFiles"
	FileService_GetFilePath_FullMethodName           = "/pb.FileService/GetFilePath"
	FileService_GetDownloadUrl_FullMethodName        = "/pb.FileService/GetDownloadUrl"
	FileService_MoveFiles_FullMethodName             = "/pb.FileService/MoveFiles"
	FileService_RenameFile_FullMethodName            = "/pb.FileService/RenameFile"
	FileService_CopyFiles_FullMethodName             = "/pb.FileService/CopyFiles"
	FileService_SoftDeleteFiles_FullMethodName       = "/pb.FileService/SoftDeleteFiles"
	FileService_ListTrash_FullMethodName             = "/pb.FileService/ListTrash"
	FileService_RestoreFiles_FullMethodName          = "/pb.FileService/RestoreFiles"
	FileService_HardDeleteFiles_FullMethodName       = "/pb.FileService/HardDeleteFiles"
	FileService_ClearTrash_FullMethodName            = "/pb.FileService/ClearTrash"
	FileService_CalcUserUsedSize_FullMethodName      = "/pb.FileService/CalcUserUsedSize"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	// -------- 上传相关 --------
	// 秒传检查 (查询 MongoDB file_meta)
	CheckInstantUpload(ctx context.Context, in *CheckInstantUploadReq, opts ...grpc.CallOption) (*CheckInstantUploadResp, error)
	// 获取预签名上传 URL
	GetPresignedUploadUrl(ctx context.Context, in *GetPresignedUploadUrlReq, opts ...grpc.CallOption) (*GetPresignedUploadUrlResp, error)
	// 创建文件记录 (上传完成后调用)
	CreateFile(ctx context.Context, in *CreateFileReq, opts ...grpc.CallOption) (*CreateFileResp, error)
	// -------- 文件夹管理 --------
	// 创建文件夹
	CreateFolder(ctx context.Context, in *CreateFolderReq, opts ...grpc.CallOption) (*CreateFolderResp, error)
	// -------- 文件查询 (供其他服务调用) --------
	// 获取单个文件信息
	GetFileInfo(ctx context.Context, in *GetFileInfoReq, opts ...grpc.CallOption) (*GetFileInfoResp, error)
	// 批量获取文件信息
	GetFilesByIds(ctx context.Context, in *GetFilesByIdsReq, opts ...grpc.CallOption) (*GetFilesByIdsResp, error)
	// 检查文件是否存在
	CheckFileExists(ctx context.Context, in *CheckFileExistsReq, opts ...grpc.CallOption) (*CheckFileExistsResp, error)
	// 列出目录内容
	ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesResp, error)
	// 获取文件路径 (面包屑)
	GetFilePath(ctx context.Context, in *GetFilePathReq, opts ...grpc.CallOption) (*GetFilePathResp, error)
	// -------- 文件操作 --------
	// 获取下载 URL
	GetDownloadUrl(ctx context.Context, in *GetDownloadUrlReq, opts ...grpc.CallOption) (*GetDownloadUrlResp, error)
	// 移动文件/文件夹
	MoveFiles(ctx context.Context, in *MoveFilesReq, opts ...grpc.CallOption) (*MoveFilesResp, error)
	// 重命名
	RenameFile(ctx context.Context, in *RenameFileReq, opts ...grpc.CallOption) (*RenameFileResp, error)
	// 复制文件/文件夹
	CopyFiles(ctx context.Context, in *CopyFilesReq, opts ...grpc.CallOption) (*CopyFilesResp, error)
	// 软删除 (移入回收站)
	SoftDeleteFiles(ctx context.Context, in *SoftDeleteFilesReq, opts ...grpc.CallOption) (*SoftDeleteFilesResp, error)
	// -------- 回收站 --------
	// 回收站列表
	ListTrash(ctx context.Context, in *ListTrashReq, opts ...grpc.CallOption) (*ListTrashResp, error)
	// 恢复文件
	RestoreFiles(ctx context.Context, in *RestoreFilesReq, opts ...grpc.CallOption) (*RestoreFilesResp, error)
	// 彻底删除
	HardDeleteFiles(ctx context.Context, in *HardDeleteFilesReq, opts ...grpc.CallOption) (*HardDeleteFilesResp, error)
	// 清空回收站
	ClearTrash(ctx context.Context, in *ClearTrashReq, opts ...grpc.CallOption) (*ClearTrashResp, error)
	// -------- 内部方法 --------
	// 计算用户已用空间
	CalcUserUsedSize(ctx context.Context, in *CalcUserUsedSizeReq, opts ...grpc.CallOption) (*CalcUserUsedSizeResp, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) CheckInstantUpload(ctx context.Context, in *CheckInstantUploadReq, opts ...grpc.CallOption) (*CheckInstantUploadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInstantUploadResp)
	err := c.cc.Invoke(ctx, FileService_CheckInstantUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetPresignedUploadUrl(ctx context.Context, in *GetPresignedUploadUrlReq, opts ...grpc.CallOption) (*GetPresignedUploadUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresignedUploadUrlResp)
	err := c.cc.Invoke(ctx, FileService_GetPresignedUploadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CreateFile(ctx context.Context, in *CreateFileReq, opts ...grpc.CallOption) (*CreateFileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileResp)
	err := c.cc.Invoke(ctx, FileService_CreateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CreateFolder(ctx context.Context, in *CreateFolderReq, opts ...grpc.CallOption) (*CreateFolderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFolderResp)
	err := c.cc.Invoke(ctx, FileService_CreateFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileInfo(ctx context.Context, in *GetFileInfoReq, opts ...grpc.CallOption) (*GetFileInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileInfoResp)
	err := c.cc.Invoke(ctx, FileService_GetFileInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFilesByIds(ctx context.Context, in *GetFilesByIdsReq, opts ...grpc.CallOption) (*GetFilesByIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFilesByIdsResp)
	err := c.cc.Invoke(ctx, FileService_GetFilesByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CheckFileExists(ctx context.Context, in *CheckFileExistsReq, opts ...grpc.CallOption) (*CheckFileExistsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckFileExistsResp)
	err := c.cc.Invoke(ctx, FileService_CheckFileExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResp)
	err := c.cc.Invoke(ctx, FileService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFilePath(ctx context.Context, in *GetFilePathReq, opts ...grpc.CallOption) (*GetFilePathResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFilePathResp)
	err := c.cc.Invoke(ctx, FileService_GetFilePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetDownloadUrl(ctx context.Context, in *GetDownloadUrlReq, opts ...grpc.CallOption) (*GetDownloadUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDownloadUrlResp)
	err := c.cc.Invoke(ctx, FileService_GetDownloadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) MoveFiles(ctx context.Context, in *MoveFilesReq, opts ...grpc.CallOption) (*MoveFilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveFilesResp)
	err := c.cc.Invoke(ctx, FileService_MoveFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) RenameFile(ctx context.Context, in *RenameFileReq, opts ...grpc.CallOption) (*RenameFileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameFileResp)
	err := c.cc.Invoke(ctx, FileService_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CopyFiles(ctx context.Context, in *CopyFilesReq, opts ...grpc.CallOption) (*CopyFilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyFilesResp)
	err := c.cc.Invoke(ctx, FileService_CopyFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) SoftDeleteFiles(ctx context.Context, in *SoftDeleteFilesReq, opts ...grpc.CallOption) (*SoftDeleteFilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftDeleteFilesResp)
	err := c.cc.Invoke(ctx, FileService_SoftDeleteFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ListTrash(ctx context.Context, in *ListTrashReq, opts ...grpc.CallOption) (*ListTrashResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrashResp)
	err := c.cc.Invoke(ctx, FileService_ListTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) RestoreFiles(ctx context.Context, in *RestoreFilesReq, opts ...grpc.CallOption) (*RestoreFilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreFilesResp)
	err := c.cc.Invoke(ctx, FileService_RestoreFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) HardDeleteFiles(ctx context.Context, in *HardDeleteFilesReq, opts ...grpc.CallOption) (*HardDeleteFilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HardDeleteFilesResp)
	err := c.cc.Invoke(ctx, FileService_HardDeleteFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ClearTrash(ctx context.Context, in *ClearTrashReq, opts ...grpc.CallOption) (*ClearTrashResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearTrashResp)
	err := c.cc.Invoke(ctx, FileService_ClearTrash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CalcUserUsedSize(ctx context.Context, in *CalcUserUsedSizeReq, opts ...grpc.CallOption) (*CalcUserUsedSizeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalcUserUsedSizeResp)
	err := c.cc.Invoke(ctx, FileService_CalcUserUsedSize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility.
type FileServiceServer interface {
	// -------- 上传相关 --------
	// 秒传检查 (查询 MongoDB file_meta)
	CheckInstantUpload(context.Context, *CheckInstantUploadReq) (*CheckInstantUploadResp, error)
	// 获取预签名上传 URL
	GetPresignedUploadUrl(context.Context, *GetPresignedUploadUrlReq) (*GetPresignedUploadUrlResp, error)
	// 创建文件记录 (上传完成后调用)
	CreateFile(context.Context, *CreateFileReq) (*CreateFileResp, error)
	// -------- 文件夹管理 --------
	// 创建文件夹
	CreateFolder(context.Context, *CreateFolderReq) (*CreateFolderResp, error)
	// -------- 文件查询 (供其他服务调用) --------
	// 获取单个文件信息
	GetFileInfo(context.Context, *GetFileInfoReq) (*GetFileInfoResp, error)
	// 批量获取文件信息
	GetFilesByIds(context.Context, *GetFilesByIdsReq) (*GetFilesByIdsResp, error)
	// 检查文件是否存在
	CheckFileExists(context.Context, *CheckFileExistsReq) (*CheckFileExistsResp, error)
	// 列出目录内容
	ListFiles(context.Context, *ListFilesReq) (*ListFilesResp, error)
	// 获取文件路径 (面包屑)
	GetFilePath(context.Context, *GetFilePathReq) (*GetFilePathResp, error)
	// -------- 文件操作 --------
	// 获取下载 URL
	GetDownloadUrl(context.Context, *GetDownloadUrlReq) (*GetDownloadUrlResp, error)
	// 移动文件/文件夹
	MoveFiles(context.Context, *MoveFilesReq) (*MoveFilesResp, error)
	// 重命名
	RenameFile(context.Context, *RenameFileReq) (*RenameFileResp, error)
	// 复制文件/文件夹
	CopyFiles(context.Context, *CopyFilesReq) (*CopyFilesResp, error)
	// 软删除 (移入回收站)
	SoftDeleteFiles(context.Context, *SoftDeleteFilesReq) (*SoftDeleteFilesResp, error)
	// -------- 回收站 --------
	// 回收站列表
	ListTrash(context.Context, *ListTrashReq) (*ListTrashResp, error)
	// 恢复文件
	RestoreFiles(context.Context, *RestoreFilesReq) (*RestoreFilesResp, error)
	// 彻底删除
	HardDeleteFiles(context.Context, *HardDeleteFilesReq) (*HardDeleteFilesResp, error)
	// 清空回收站
	ClearTrash(context.Context, *ClearTrashReq) (*ClearTrashResp, error)
	// -------- 内部方法 --------
	// 计算用户已用空间
	CalcUserUsedSize(context.Context, *CalcUserUsedSizeReq) (*CalcUserUsedSizeResp, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServiceServer struct{}

func (UnimplementedFileServiceServer) CheckInstantUpload(context.Context, *CheckInstantUploadReq) (*CheckInstantUploadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckInstantUpload not implemented")
}
func (UnimplementedFileServiceServer) GetPresignedUploadUrl(context.Context, *GetPresignedUploadUrlReq) (*GetPresignedUploadUrlResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresignedUploadUrl not implemented")
}
func (UnimplementedFileServiceServer) CreateFile(context.Context, *CreateFileReq) (*CreateFileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFile not implemented")
}
func (UnimplementedFileServiceServer) CreateFolder(context.Context, *CreateFolderReq) (*CreateFolderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFolder not implemented")
}
func (UnimplementedFileServiceServer) GetFileInfo(context.Context, *GetFileInfoReq) (*GetFileInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileInfo not implemented")
}
func (UnimplementedFileServiceServer) GetFilesByIds(context.Context, *GetFilesByIdsReq) (*GetFilesByIdsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFilesByIds not implemented")
}
func (UnimplementedFileServiceServer) CheckFileExists(context.Context, *CheckFileExistsReq) (*CheckFileExistsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckFileExists not implemented")
}
func (UnimplementedFileServiceServer) ListFiles(context.Context, *ListFilesReq) (*ListFilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedFileServiceServer) GetFilePath(context.Context, *GetFilePathReq) (*GetFilePathResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFilePath not implemented")
}
func (UnimplementedFileServiceServer) GetDownloadUrl(context.Context, *GetDownloadUrlReq) (*GetDownloadUrlResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDownloadUrl not implemented")
}
func (UnimplementedFileServiceServer) MoveFiles(context.Context, *MoveFilesReq) (*MoveFilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveFiles not implemented")
}
func (UnimplementedFileServiceServer) RenameFile(context.Context, *RenameFileReq) (*RenameFileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedFileServiceServer) CopyFiles(context.Context, *CopyFilesReq) (*CopyFilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyFiles not implemented")
}
func (UnimplementedFileServiceServer) SoftDeleteFiles(context.Context, *SoftDeleteFilesReq) (*SoftDeleteFilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SoftDeleteFiles not implemented")
}
func (UnimplementedFileServiceServer) ListTrash(context.Context, *ListTrashReq) (*ListTrashResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrash not implemented")
}
func (UnimplementedFileServiceServer) RestoreFiles(context.Context, *RestoreFilesReq) (*RestoreFilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreFiles not implemented")
}
func (UnimplementedFileServiceServer) HardDeleteFiles(context.Context, *HardDeleteFilesReq) (*HardDeleteFilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HardDeleteFiles not implemented")
}
func (UnimplementedFileServiceServer) ClearTrash(context.Context, *ClearTrashReq) (*ClearTrashResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearTrash not implemented")
}
func (UnimplementedFileServiceServer) CalcUserUsedSize(context.Context, *CalcUserUsedSizeReq) (*CalcUserUsedSizeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CalcUserUsedSize not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}
func (UnimplementedFileServiceServer) testEmbeddedByValue()                     {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	// If the following call panics, it indicates UnimplementedFileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_CheckInstantUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInstantUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CheckInstantUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CheckInstantUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CheckInstantUpload(ctx, req.(*CheckInstantUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetPresignedUploadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedUploadUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetPresignedUploadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetPresignedUploadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetPresignedUploadUrl(ctx, req.(*GetPresignedUploadUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CreateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CreateFile(ctx, req.(*CreateFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CreateFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFolderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CreateFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CreateFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CreateFolder(ctx, req.(*CreateFolderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFileInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileInfo(ctx, req.(*GetFileInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFilesByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFilesByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFilesByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFilesByIds(ctx, req.(*GetFilesByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CheckFileExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFileExistsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CheckFileExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CheckFileExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CheckFileExists(ctx, req.(*CheckFileExistsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ListFiles(ctx, req.(*ListFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFilePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilePathReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFilePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetFilePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFilePath(ctx, req.(*GetFilePathReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetDownloadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownloadUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetDownloadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetDownloadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetDownloadUrl(ctx, req.(*GetDownloadUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_MoveFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).MoveFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_MoveFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).MoveFiles(ctx, req.(*MoveFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).RenameFile(ctx, req.(*RenameFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CopyFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CopyFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CopyFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CopyFiles(ctx, req.(*CopyFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_SoftDeleteFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoftDeleteFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).SoftDeleteFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_SoftDeleteFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).SoftDeleteFiles(ctx, req.(*SoftDeleteFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ListTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrashReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ListTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ListTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ListTrash(ctx, req.(*ListTrashReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_RestoreFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).RestoreFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_RestoreFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).RestoreFiles(ctx, req.(*RestoreFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_HardDeleteFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HardDeleteFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).HardDeleteFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_HardDeleteFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).HardDeleteFiles(ctx, req.(*HardDeleteFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ClearTrash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearTrashReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).ClearTrash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_ClearTrash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).ClearTrash(ctx, req.(*ClearTrashReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CalcUserUsedSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcUserUsedSizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CalcUserUsedSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_CalcUserUsedSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CalcUserUsedSize(ctx, req.(*CalcUserUsedSizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckInstantUpload",
			Handler:    _FileService_CheckInstantUpload_Handler,
		},
		{
			MethodName: "GetPresignedUploadUrl",
			Handler:    _FileService_GetPresignedUploadUrl_Handler,
		},
		{
			MethodName: "CreateFile",
			Handler:    _FileService_CreateFile_Handler,
		},
		{
			MethodName: "CreateFolder",
			Handler:    _FileService_CreateFolder_Handler,
		},
		{
			MethodName: "GetFileInfo",
			Handler:    _FileService_GetFileInfo_Handler,
		},
		{
			MethodName: "GetFilesByIds",
			Handler:    _FileService_GetFilesByIds_Handler,
		},
		{
			MethodName: "CheckFileExists",
			Handler:    _FileService_CheckFileExists_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _FileService_ListFiles_Handler,
		},
		{
			MethodName: "GetFilePath",
			Handler:    _FileService_GetFilePath_Handler,
		},
		{
			MethodName: "GetDownloadUrl",
			Handler:    _FileService_GetDownloadUrl_Handler,
		},
		{
			MethodName: "MoveFiles",
			Handler:    _FileService_MoveFiles_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _FileService_RenameFile_Handler,
		},
		{
			MethodName: "CopyFiles",
			Handler:    _FileService_CopyFiles_Handler,
		},
		{
			MethodName: "SoftDeleteFiles",
			Handler:    _FileService_SoftDeleteFiles_Handler,
		},
		{
			MethodName: "ListTrash",
			Handler:    _FileService_ListTrash_Handler,
		},
		{
			MethodName: "RestoreFiles",
			Handler:    _FileService_RestoreFiles_Handler,
		},
		{
			MethodName: "HardDeleteFiles",
			Handler:    _FileService_HardDeleteFiles_Handler,
		},
		{
			MethodName: "ClearTrash",
			Handler:    _FileService_ClearTrash_Handler,
		},
		{
			MethodName: "CalcUserUsedSize",
			Handler:    _FileService_CalcUserUsedSize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/file/cmd/rpc/pb/file.proto",
}
