// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: app/file/cmd/rpc/pb/file.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文件/文件夹信息
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`       // 文件唯一标识 (UUID)
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`               // 文件 SHA256
	UserId        int64                  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`          // 所属用户ID
	ParentId      int64                  `protobuf:"varint,5,opt,name=parentId,proto3" json:"parentId,omitempty"`      // 父目录ID (0=根目录)
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`               // 文件名
	Ext           string                 `protobuf:"bytes,7,opt,name=ext,proto3" json:"ext,omitempty"`                 // 扩展名 (文件夹为空)
	Size          uint64                 `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`              // 文件大小 (字节)
	Path          string                 `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`               // S3 存储路径
	IsDir         bool                   `protobuf:"varint,10,opt,name=isDir,proto3" json:"isDir,omitempty"`           // 是否为文件夹
	CreateTime    int64                  `protobuf:"varint,11,opt,name=createTime,proto3" json:"createTime,omitempty"` // 创建时间戳
	UpdateTime    int64                  `protobuf:"varint,12,opt,name=updateTime,proto3" json:"updateTime,omitempty"` // 更新时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileInfo) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *FileInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FileInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FileInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 文件元数据 (MongoDB file_meta)
type FileMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`              // MongoDB ObjectId
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`          // 文件 SHA256
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`         // 文件大小
	S3Key         string                 `protobuf:"bytes,4,opt,name=s3Key,proto3" json:"s3Key,omitempty"`        // S3 存储路径
	Ext           string                 `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`            // 扩展名
	MimeType      string                 `protobuf:"bytes,6,opt,name=mimeType,proto3" json:"mimeType,omitempty"`  // MIME 类型
	RefCount      int64                  `protobuf:"varint,7,opt,name=refCount,proto3" json:"refCount,omitempty"` // 引用计数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileMeta) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileMeta) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMeta) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *FileMeta) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *FileMeta) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileMeta) GetRefCount() int64 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

// --- 秒传检查 ---
type CheckInstantUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`  // 文件 SHA256
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 文件大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInstantUploadReq) Reset() {
	*x = CheckInstantUploadReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInstantUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInstantUploadReq) ProtoMessage() {}

func (x *CheckInstantUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInstantUploadReq.ProtoReflect.Descriptor instead.
func (*CheckInstantUploadReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{2}
}

func (x *CheckInstantUploadReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *CheckInstantUploadReq) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CheckInstantUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"` // 是否存在 (可秒传)
	Meta          *FileMeta              `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`      // 存在时返回元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInstantUploadResp) Reset() {
	*x = CheckInstantUploadResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInstantUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInstantUploadResp) ProtoMessage() {}

func (x *CheckInstantUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInstantUploadResp.ProtoReflect.Descriptor instead.
func (*CheckInstantUploadResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{3}
}

func (x *CheckInstantUploadResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckInstantUploadResp) GetMeta() *FileMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// --- 获取预签名上传URL ---
type GetPresignedUploadUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`         // 文件 SHA256
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`        // 文件大小
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`         // 文件名
	Ext           string                 `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`           // 扩展名
	MimeType      string                 `protobuf:"bytes,6,opt,name=mimeType,proto3" json:"mimeType,omitempty"` // MIME 类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedUploadUrlReq) Reset() {
	*x = GetPresignedUploadUrlReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedUploadUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedUploadUrlReq) ProtoMessage() {}

func (x *GetPresignedUploadUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedUploadUrlReq.ProtoReflect.Descriptor instead.
func (*GetPresignedUploadUrlReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{4}
}

func (x *GetPresignedUploadUrlReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPresignedUploadUrlReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetPresignedUploadUrlReq) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetPresignedUploadUrlReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPresignedUploadUrlReq) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *GetPresignedUploadUrlReq) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type GetPresignedUploadUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=uploadUrl,proto3" json:"uploadUrl,omitempty"` // S3 预签名上传 URL
	S3Key         string                 `protobuf:"bytes,2,opt,name=s3Key,proto3" json:"s3Key,omitempty"`         // S3 存储路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedUploadUrlResp) Reset() {
	*x = GetPresignedUploadUrlResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedUploadUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedUploadUrlResp) ProtoMessage() {}

func (x *GetPresignedUploadUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedUploadUrlResp.ProtoReflect.Descriptor instead.
func (*GetPresignedUploadUrlResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{5}
}

func (x *GetPresignedUploadUrlResp) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetPresignedUploadUrlResp) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

// --- 创建文件记录 (上传完成后调用) ---
type CreateFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"` // 父目录ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`          // 文件名
	Ext           string                 `protobuf:"bytes,4,opt,name=ext,proto3" json:"ext,omitempty"`            // 扩展名
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`          // 文件 SHA256
	Size          uint64                 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`         // 文件大小
	S3Key         string                 `protobuf:"bytes,7,opt,name=s3Key,proto3" json:"s3Key,omitempty"`        // S3 存储路径
	MimeType      string                 `protobuf:"bytes,8,opt,name=mimeType,proto3" json:"mimeType,omitempty"`  // MIME 类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileReq) Reset() {
	*x = CreateFileReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileReq) ProtoMessage() {}

func (x *CreateFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileReq.ProtoReflect.Descriptor instead.
func (*CreateFileReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{6}
}

func (x *CreateFileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateFileReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateFileReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFileReq) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *CreateFileReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *CreateFileReq) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CreateFileReq) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *CreateFileReq) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type CreateFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"` // 文件唯一标识
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`            // 文件ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResp) Reset() {
	*x = CreateFileResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResp) ProtoMessage() {}

func (x *CreateFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResp.ProtoReflect.Descriptor instead.
func (*CreateFileResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{7}
}

func (x *CreateFileResp) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *CreateFileResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// --- 创建文件夹 ---
type CreateFolderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"` // 父目录ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`          // 文件夹名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderReq) Reset() {
	*x = CreateFolderReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderReq) ProtoMessage() {}

func (x *CreateFolderReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderReq.ProtoReflect.Descriptor instead.
func (*CreateFolderReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{8}
}

func (x *CreateFolderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateFolderReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateFolderReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFolderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"` // 文件夹唯一标识
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`            // 文件夹ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFolderResp) Reset() {
	*x = CreateFolderResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFolderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFolderResp) ProtoMessage() {}

func (x *CreateFolderResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFolderResp.ProtoReflect.Descriptor instead.
func (*CreateFolderResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{9}
}

func (x *CreateFolderResp) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *CreateFolderResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// --- 获取文件信息 (供 Share 等服务调用) ---
type GetFileInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"` // 文件标识
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`    // 用户ID (可选，用于权限验证)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoReq) Reset() {
	*x = GetFileInfoReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoReq) ProtoMessage() {}

func (x *GetFileInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoReq.ProtoReflect.Descriptor instead.
func (*GetFileInfoReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileInfoReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetFileInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFileInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoResp) Reset() {
	*x = GetFileInfoResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoResp) ProtoMessage() {}

func (x *GetFileInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoResp.ProtoReflect.Descriptor instead.
func (*GetFileInfoResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileInfoResp) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

// --- 批量获取文件信息 ---
type GetFilesByIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []string               `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"` // 文件标识列表
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`        // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesByIdsReq) Reset() {
	*x = GetFilesByIdsReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesByIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByIdsReq) ProtoMessage() {}

func (x *GetFilesByIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByIdsReq.ProtoReflect.Descriptor instead.
func (*GetFilesByIdsReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{12}
}

func (x *GetFilesByIdsReq) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *GetFilesByIdsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFilesByIdsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesByIdsResp) Reset() {
	*x = GetFilesByIdsResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesByIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesByIdsResp) ProtoMessage() {}

func (x *GetFilesByIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesByIdsResp.ProtoReflect.Descriptor instead.
func (*GetFilesByIdsResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{13}
}

func (x *GetFilesByIdsResp) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

// --- 检查文件是否存在 ---
type CheckFileExistsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFileExistsReq) Reset() {
	*x = CheckFileExistsReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFileExistsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFileExistsReq) ProtoMessage() {}

func (x *CheckFileExistsReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFileExistsReq.ProtoReflect.Descriptor instead.
func (*CheckFileExistsReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{14}
}

func (x *CheckFileExistsReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *CheckFileExistsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckFileExistsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFileExistsResp) Reset() {
	*x = CheckFileExistsResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFileExistsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFileExistsResp) ProtoMessage() {}

func (x *CheckFileExistsResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFileExistsResp.ProtoReflect.Descriptor instead.
func (*CheckFileExistsResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{15}
}

func (x *CheckFileExistsResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// --- 列出目录内容 ---
type ListFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"` // 父目录ID (0=根目录)
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	OrderBy       string                 `protobuf:"bytes,5,opt,name=orderBy,proto3" json:"orderBy,omitempty"` // 排序字段: name, size, create_time
	Order         string                 `protobuf:"bytes,6,opt,name=order,proto3" json:"order,omitempty"`     // 排序方向: asc, desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesReq) Reset() {
	*x = ListFilesReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesReq) ProtoMessage() {}

func (x *ListFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesReq.ProtoReflect.Descriptor instead.
func (*ListFilesReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{16}
}

func (x *ListFilesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFilesReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ListFilesReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFilesReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFilesReq) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListFilesReq) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type ListFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FileInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResp) Reset() {
	*x = ListFilesResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResp) ProtoMessage() {}

func (x *ListFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResp.ProtoReflect.Descriptor instead.
func (*ListFilesResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{17}
}

func (x *ListFilesResp) GetList() []*FileInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListFilesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- 获取文件路径 (面包屑导航) ---
type GetFilePathReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilePathReq) Reset() {
	*x = GetFilePathReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilePathReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilePathReq) ProtoMessage() {}

func (x *GetFilePathReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilePathReq.ProtoReflect.Descriptor instead.
func (*GetFilePathReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{18}
}

func (x *GetFilePathReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetFilePathReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFilePathResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []*FileInfo            `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"` // 从根目录到当前文件的路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilePathResp) Reset() {
	*x = GetFilePathResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilePathResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilePathResp) ProtoMessage() {}

func (x *GetFilePathResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilePathResp.ProtoReflect.Descriptor instead.
func (*GetFilePathResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{19}
}

func (x *GetFilePathResp) GetPath() []*FileInfo {
	if x != nil {
		return x.Path
	}
	return nil
}

// --- 获取下载URL ---
type GetDownloadUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlReq) Reset() {
	*x = GetDownloadUrlReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlReq) ProtoMessage() {}

func (x *GetDownloadUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlReq.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{20}
}

func (x *GetDownloadUrlReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetDownloadUrlReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetDownloadUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // 预签名下载 URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlResp) Reset() {
	*x = GetDownloadUrlResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResp) ProtoMessage() {}

func (x *GetDownloadUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResp.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{21}
}

func (x *GetDownloadUrlResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// --- 移动文件/文件夹 ---
type MoveFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Identities    []string               `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"` // 文件标识列表
	TargetId      int64                  `protobuf:"varint,3,opt,name=targetId,proto3" json:"targetId,omitempty"`    // 目标目录ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFilesReq) Reset() {
	*x = MoveFilesReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFilesReq) ProtoMessage() {}

func (x *MoveFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFilesReq.ProtoReflect.Descriptor instead.
func (*MoveFilesReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{22}
}

func (x *MoveFilesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MoveFilesReq) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *MoveFilesReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type MoveFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovedCount    int64                  `protobuf:"varint,1,opt,name=movedCount,proto3" json:"movedCount,omitempty"` // 成功移动的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFilesResp) Reset() {
	*x = MoveFilesResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFilesResp) ProtoMessage() {}

func (x *MoveFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFilesResp.ProtoReflect.Descriptor instead.
func (*MoveFilesResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{23}
}

func (x *MoveFilesResp) GetMovedCount() int64 {
	if x != nil {
		return x.MovedCount
	}
	return 0
}

// --- 重命名 ---
type RenameFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // 新名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileReq) Reset() {
	*x = RenameFileReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileReq) ProtoMessage() {}

func (x *RenameFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileReq.ProtoReflect.Descriptor instead.
func (*RenameFileReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{24}
}

func (x *RenameFileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RenameFileReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *RenameFileReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RenameFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileResp) Reset() {
	*x = RenameFileResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileResp) ProtoMessage() {}

func (x *RenameFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileResp.ProtoReflect.Descriptor instead.
func (*RenameFileResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{25}
}

// --- 复制文件/文件夹 ---
type CopyFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"` // 源文件所有者ID
	Identities    []string               `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=targetId,proto3" json:"targetId,omitempty"`         // 目标目录ID
	TargetUserId  int64                  `protobuf:"varint,4,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"` // 目标用户ID（跨用户复制时使用，0表示同用户）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFilesReq) Reset() {
	*x = CopyFilesReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFilesReq) ProtoMessage() {}

func (x *CopyFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFilesReq.ProtoReflect.Descriptor instead.
func (*CopyFilesReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{26}
}

func (x *CopyFilesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CopyFilesReq) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *CopyFilesReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CopyFilesReq) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type CopyFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CopiedCount   int64                  `protobuf:"varint,1,opt,name=copiedCount,proto3" json:"copiedCount,omitempty"` // 成功复制的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFilesResp) Reset() {
	*x = CopyFilesResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFilesResp) ProtoMessage() {}

func (x *CopyFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFilesResp.ProtoReflect.Descriptor instead.
func (*CopyFilesResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{27}
}

func (x *CopyFilesResp) GetCopiedCount() int64 {
	if x != nil {
		return x.CopiedCount
	}
	return 0
}

// --- 软删除 (移入回收站) ---
type SoftDeleteFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Identities    []string               `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftDeleteFilesReq) Reset() {
	*x = SoftDeleteFilesReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftDeleteFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftDeleteFilesReq) ProtoMessage() {}

func (x *SoftDeleteFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftDeleteFilesReq.ProtoReflect.Descriptor instead.
func (*SoftDeleteFilesReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{28}
}

func (x *SoftDeleteFilesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SoftDeleteFilesReq) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

type SoftDeleteFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deletedCount,proto3" json:"deletedCount,omitempty"`
	FreedSize     uint64                 `protobuf:"varint,2,opt,name=freedSize,proto3" json:"freedSize,omitempty"` // 释放的空间大小 (用于退还配额)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftDeleteFilesResp) Reset() {
	*x = SoftDeleteFilesResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftDeleteFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftDeleteFilesResp) ProtoMessage() {}

func (x *SoftDeleteFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftDeleteFilesResp.ProtoReflect.Descriptor instead.
func (*SoftDeleteFilesResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{29}
}

func (x *SoftDeleteFilesResp) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *SoftDeleteFilesResp) GetFreedSize() uint64 {
	if x != nil {
		return x.FreedSize
	}
	return 0
}

// --- 回收站列表 ---
type ListTrashReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashReq) Reset() {
	*x = ListTrashReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashReq) ProtoMessage() {}

func (x *ListTrashReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashReq.ProtoReflect.Descriptor instead.
func (*ListTrashReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{30}
}

func (x *ListTrashReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTrashReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTrashReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTrashResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FileInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashResp) Reset() {
	*x = ListTrashResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashResp) ProtoMessage() {}

func (x *ListTrashResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashResp.ProtoReflect.Descriptor instead.
func (*ListTrashResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{31}
}

func (x *ListTrashResp) GetList() []*FileInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListTrashResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- 恢复文件 ---
type RestoreFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Identities    []string               `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFilesReq) Reset() {
	*x = RestoreFilesReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFilesReq) ProtoMessage() {}

func (x *RestoreFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFilesReq.ProtoReflect.Descriptor instead.
func (*RestoreFilesReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{32}
}

func (x *RestoreFilesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RestoreFilesReq) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

type RestoreFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestoredCount int64                  `protobuf:"varint,1,opt,name=restoredCount,proto3" json:"restoredCount,omitempty"`
	UsedSize      uint64                 `protobuf:"varint,2,opt,name=usedSize,proto3" json:"usedSize,omitempty"` // 恢复后占用的空间 (用于扣减配额)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFilesResp) Reset() {
	*x = RestoreFilesResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFilesResp) ProtoMessage() {}

func (x *RestoreFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFilesResp.ProtoReflect.Descriptor instead.
func (*RestoreFilesResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{33}
}

func (x *RestoreFilesResp) GetRestoredCount() int64 {
	if x != nil {
		return x.RestoredCount
	}
	return 0
}

func (x *RestoreFilesResp) GetUsedSize() uint64 {
	if x != nil {
		return x.UsedSize
	}
	return 0
}

// --- 彻底删除 ---
type HardDeleteFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Identities    []string               `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardDeleteFilesReq) Reset() {
	*x = HardDeleteFilesReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardDeleteFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardDeleteFilesReq) ProtoMessage() {}

func (x *HardDeleteFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardDeleteFilesReq.ProtoReflect.Descriptor instead.
func (*HardDeleteFilesReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{34}
}

func (x *HardDeleteFilesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HardDeleteFilesReq) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

type HardDeleteFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deletedCount,proto3" json:"deletedCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardDeleteFilesResp) Reset() {
	*x = HardDeleteFilesResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardDeleteFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardDeleteFilesResp) ProtoMessage() {}

func (x *HardDeleteFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardDeleteFilesResp.ProtoReflect.Descriptor instead.
func (*HardDeleteFilesResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{35}
}

func (x *HardDeleteFilesResp) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

// --- 清空回收站 ---
type ClearTrashReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearTrashReq) Reset() {
	*x = ClearTrashReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearTrashReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearTrashReq) ProtoMessage() {}

func (x *ClearTrashReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearTrashReq.ProtoReflect.Descriptor instead.
func (*ClearTrashReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{36}
}

func (x *ClearTrashReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ClearTrashResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deletedCount,proto3" json:"deletedCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearTrashResp) Reset() {
	*x = ClearTrashResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearTrashResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearTrashResp) ProtoMessage() {}

func (x *ClearTrashResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearTrashResp.ProtoReflect.Descriptor instead.
func (*ClearTrashResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{37}
}

func (x *ClearTrashResp) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

// --- 计算用户已用空间 ---
type CalcUserUsedSizeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcUserUsedSizeReq) Reset() {
	*x = CalcUserUsedSizeReq{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcUserUsedSizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcUserUsedSizeReq) ProtoMessage() {}

func (x *CalcUserUsedSizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcUserUsedSizeReq.ProtoReflect.Descriptor instead.
func (*CalcUserUsedSizeReq) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{38}
}

func (x *CalcUserUsedSizeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CalcUserUsedSizeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedSize      uint64                 `protobuf:"varint,1,opt,name=usedSize,proto3" json:"usedSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcUserUsedSizeResp) Reset() {
	*x = CalcUserUsedSizeResp{}
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcUserUsedSizeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcUserUsedSizeResp) ProtoMessage() {}

func (x *CalcUserUsedSizeResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_file_cmd_rpc_pb_file_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcUserUsedSizeResp.ProtoReflect.Descriptor instead.
func (*CalcUserUsedSizeResp) Descriptor() ([]byte, []int) {
	return file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP(), []int{39}
}

func (x *CalcUserUsedSizeResp) GetUsedSize() uint64 {
	if x != nil {
		return x.UsedSize
	}
	return 0
}

var File_app_file_cmd_rpc_pb_file_proto protoreflect.FileDescriptor

const file_app_file_cmd_rpc_pb_file_proto_rawDesc = "" +
	"\n" +
	"\x1eapp/file/cmd/rpc/pb/file.proto\x12\x02pb\"\xa2\x02\n" +
	"\bFileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bparentId\x18\x05 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x10\n" +
	"\x03ext\x18\a \x01(\tR\x03ext\x12\x12\n" +
	"\x04size\x18\b \x01(\x04R\x04size\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12\x14\n" +
	"\x05isDir\x18\n" +
	" \x01(\bR\x05isDir\x12\x1e\n" +
	"\n" +
	"createTime\x18\v \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\f \x01(\x03R\n" +
	"updateTime\"\xa2\x01\n" +
	"\bFileMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x14\n" +
	"\x05s3Key\x18\x04 \x01(\tR\x05s3Key\x12\x10\n" +
	"\x03ext\x18\x05 \x01(\tR\x03ext\x12\x1a\n" +
	"\bmimeType\x18\x06 \x01(\tR\bmimeType\x12\x1a\n" +
	"\brefCount\x18\a \x01(\x03R\brefCount\"?\n" +
	"\x15CheckInstantUploadReq\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"R\n" +
	"\x16CheckInstantUploadResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12 \n" +
	"\x04meta\x18\x02 \x01(\v2\f.pb.FileMetaR\x04meta\"\x9c\x01\n" +
	"\x18GetPresignedUploadUrlReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03ext\x18\x05 \x01(\tR\x03ext\x12\x1a\n" +
	"\bmimeType\x18\x06 \x01(\tR\bmimeType\"O\n" +
	"\x19GetPresignedUploadUrlResp\x12\x1c\n" +
	"\tuploadUrl\x18\x01 \x01(\tR\tuploadUrl\x12\x14\n" +
	"\x05s3Key\x18\x02 \x01(\tR\x05s3Key\"\xc3\x01\n" +
	"\rCreateFileReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bparentId\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03ext\x18\x04 \x01(\tR\x03ext\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x04R\x04size\x12\x14\n" +
	"\x05s3Key\x18\a \x01(\tR\x05s3Key\x12\x1a\n" +
	"\bmimeType\x18\b \x01(\tR\bmimeType\"<\n" +
	"\x0eCreateFileResp\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"Y\n" +
	"\x0fCreateFolderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bparentId\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\">\n" +
	"\x10CreateFolderResp\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"D\n" +
	"\x0eGetFileInfoReq\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"3\n" +
	"\x0fGetFileInfoResp\x12 \n" +
	"\x04file\x18\x01 \x01(\v2\f.pb.FileInfoR\x04file\"J\n" +
	"\x10GetFilesByIdsReq\x12\x1e\n" +
	"\n" +
	"identities\x18\x01 \x03(\tR\n" +
	"identities\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"7\n" +
	"\x11GetFilesByIdsResp\x12\"\n" +
	"\x05files\x18\x01 \x03(\v2\f.pb.FileInfoR\x05files\"H\n" +
	"\x12CheckFileExistsReq\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"-\n" +
	"\x13CheckFileExistsResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\xa2\x01\n" +
	"\fListFilesReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bparentId\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\x12\x18\n" +
	"\aorderBy\x18\x05 \x01(\tR\aorderBy\x12\x14\n" +
	"\x05order\x18\x06 \x01(\tR\x05order\"G\n" +
	"\rListFilesResp\x12 \n" +
	"\x04list\x18\x01 \x03(\v2\f.pb.FileInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"D\n" +
	"\x0eGetFilePathReq\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"3\n" +
	"\x0fGetFilePathResp\x12 \n" +
	"\x04path\x18\x01 \x03(\v2\f.pb.FileInfoR\x04path\"G\n" +
	"\x11GetDownloadUrlReq\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"&\n" +
	"\x12GetDownloadUrlResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"b\n" +
	"\fMoveFilesReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"identities\x18\x02 \x03(\tR\n" +
	"identities\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\x03R\btargetId\"/\n" +
	"\rMoveFilesResp\x12\x1e\n" +
	"\n" +
	"movedCount\x18\x01 \x01(\x03R\n" +
	"movedCount\"W\n" +
	"\rRenameFileReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x10\n" +
	"\x0eRenameFileResp\"\x86\x01\n" +
	"\fCopyFilesReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"identities\x18\x02 \x03(\tR\n" +
	"identities\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\x03R\btargetId\x12\"\n" +
	"\ftargetUserId\x18\x04 \x01(\x03R\ftargetUserId\"1\n" +
	"\rCopyFilesResp\x12 \n" +
	"\vcopiedCount\x18\x01 \x01(\x03R\vcopiedCount\"L\n" +
	"\x12SoftDeleteFilesReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"identities\x18\x02 \x03(\tR\n" +
	"identities\"W\n" +
	"\x13SoftDeleteFilesResp\x12\"\n" +
	"\fdeletedCount\x18\x01 \x01(\x03R\fdeletedCount\x12\x1c\n" +
	"\tfreedSize\x18\x02 \x01(\x04R\tfreedSize\"V\n" +
	"\fListTrashReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"G\n" +
	"\rListTrashResp\x12 \n" +
	"\x04list\x18\x01 \x03(\v2\f.pb.FileInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"I\n" +
	"\x0fRestoreFilesReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"identities\x18\x02 \x03(\tR\n" +
	"identities\"T\n" +
	"\x10RestoreFilesResp\x12$\n" +
	"\rrestoredCount\x18\x01 \x01(\x03R\rrestoredCount\x12\x1a\n" +
	"\busedSize\x18\x02 \x01(\x04R\busedSize\"L\n" +
	"\x12HardDeleteFilesReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"identities\x18\x02 \x03(\tR\n" +
	"identities\"9\n" +
	"\x13HardDeleteFilesResp\x12\"\n" +
	"\fdeletedCount\x18\x01 \x01(\x03R\fdeletedCount\"'\n" +
	"\rClearTrashReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"4\n" +
	"\x0eClearTrashResp\x12\"\n" +
	"\fdeletedCount\x18\x01 \x01(\x03R\fdeletedCount\"-\n" +
	"\x13CalcUserUsedSizeReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"2\n" +
	"\x14CalcUserUsedSizeResp\x12\x1a\n" +
	"\busedSize\x18\x01 \x01(\x04R\busedSize2\x8f\t\n" +
	"\vFileService\x12K\n" +
	"\x12CheckInstantUpload\x12\x19.pb.CheckInstantUploadReq\x1a\x1a.pb.CheckInstantUploadResp\x12T\n" +
	"\x15GetPresignedUploadUrl\x12\x1c.pb.GetPresignedUploadUrlReq\x1a\x1d.pb.GetPresignedUploadUrlResp\x123\n" +
	"\n" +
	"CreateFile\x12\x11.pb.CreateFileReq\x1a\x12.pb.CreateFileResp\x129\n" +
	"\fCreateFolder\x12\x13.pb.CreateFolderReq\x1a\x14.pb.CreateFolderResp\x126\n" +
	"\vGetFileInfo\x12\x12.pb.GetFileInfoReq\x1a\x13.pb.GetFileInfoResp\x12<\n" +
	"\rGetFilesByIds\x12\x14.pb.GetFilesByIdsReq\x1a\x15.pb.GetFilesByIdsResp\x12B\n" +
	"\x0fCheckFileExists\x12\x16.pb.CheckFileExistsReq\x1a\x17.pb.CheckFileExistsResp\x120\n" +
	"\tListFiles\x12\x10.pb.ListFilesReq\x1a\x11.pb.ListFilesResp\x126\n" +
	"\vGetFilePath\x12\x12.pb.GetFilePathReq\x1a\x13.pb.GetFilePathResp\x12?\n" +
	"\x0eGetDownloadUrl\x12\x15.pb.GetDownloadUrlReq\x1a\x16.pb.GetDownloadUrlResp\x120\n" +
	"\tMoveFiles\x12\x10.pb.MoveFilesReq\x1a\x11.pb.MoveFilesResp\x123\n" +
	"\n" +
	"RenameFile\x12\x11.pb.RenameFileReq\x1a\x12.pb.RenameFileResp\x120\n" +
	"\tCopyFiles\x12\x10.pb.CopyFilesReq\x1a\x11.pb.CopyFilesResp\x12B\n" +
	"\x0fSoftDeleteFiles\x12\x16.pb.SoftDeleteFilesReq\x1a\x17.pb.SoftDeleteFilesResp\x120\n" +
	"\tListTrash\x12\x10.pb.ListTrashReq\x1a\x11.pb.ListTrashResp\x129\n" +
	"\fRestoreFiles\x12\x13.pb.RestoreFilesReq\x1a\x14.pb.RestoreFilesResp\x12B\n" +
	"\x0fHardDeleteFiles\x12\x16.pb.HardDeleteFilesReq\x1a\x17.pb.HardDeleteFilesResp\x123\n" +
	"\n" +
	"ClearTrash\x12\x11.pb.ClearTrashReq\x1a\x12.pb.ClearTrashResp\x12E\n" +
	"\x10CalcUserUsedSize\x12\x17.pb.CalcUserUsedSizeReq\x1a\x18.pb.CalcUserUsedSizeRespB\x06Z\x04./pbb\x06proto3"

var (
	file_app_file_cmd_rpc_pb_file_proto_rawDescOnce sync.Once
	file_app_file_cmd_rpc_pb_file_proto_rawDescData []byte
)

func file_app_file_cmd_rpc_pb_file_proto_rawDescGZIP() []byte {
	file_app_file_cmd_rpc_pb_file_proto_rawDescOnce.Do(func() {
		file_app_file_cmd_rpc_pb_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_file_cmd_rpc_pb_file_proto_rawDesc), len(file_app_file_cmd_rpc_pb_file_proto_rawDesc)))
	})
	return file_app_file_cmd_rpc_pb_file_proto_rawDescData
}

var file_app_file_cmd_rpc_pb_file_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_app_file_cmd_rpc_pb_file_proto_goTypes = []any{
	(*FileInfo)(nil),                  // 0: pb.FileInfo
	(*FileMeta)(nil),                  // 1: pb.FileMeta
	(*CheckInstantUploadReq)(nil),     // 2: pb.CheckInstantUploadReq
	(*CheckInstantUploadResp)(nil),    // 3: pb.CheckInstantUploadResp
	(*GetPresignedUploadUrlReq)(nil),  // 4: pb.GetPresignedUploadUrlReq
	(*GetPresignedUploadUrlResp)(nil), // 5: pb.GetPresignedUploadUrlResp
	(*CreateFileReq)(nil),             // 6: pb.CreateFileReq
	(*CreateFileResp)(nil),            // 7: pb.CreateFileResp
	(*CreateFolderReq)(nil),           // 8: pb.CreateFolderReq
	(*CreateFolderResp)(nil),          // 9: pb.CreateFolderResp
	(*GetFileInfoReq)(nil),            // 10: pb.GetFileInfoReq
	(*GetFileInfoResp)(nil),           // 11: pb.GetFileInfoResp
	(*GetFilesByIdsReq)(nil),          // 12: pb.GetFilesByIdsReq
	(*GetFilesByIdsResp)(nil),         // 13: pb.GetFilesByIdsResp
	(*CheckFileExistsReq)(nil),        // 14: pb.CheckFileExistsReq
	(*CheckFileExistsResp)(nil),       // 15: pb.CheckFileExistsResp
	(*ListFilesReq)(nil),              // 16: pb.ListFilesReq
	(*ListFilesResp)(nil),             // 17: pb.ListFilesResp
	(*GetFilePathReq)(nil),            // 18: pb.GetFilePathReq
	(*GetFilePathResp)(nil),           // 19: pb.GetFilePathResp
	(*GetDownloadUrlReq)(nil),         // 20: pb.GetDownloadUrlReq
	(*GetDownloadUrlResp)(nil),        // 21: pb.GetDownloadUrlResp
	(*MoveFilesReq)(nil),              // 22: pb.MoveFilesReq
	(*MoveFilesResp)(nil),             // 23: pb.MoveFilesResp
	(*RenameFileReq)(nil),             // 24: pb.RenameFileReq
	(*RenameFileResp)(nil),            // 25: pb.RenameFileResp
	(*CopyFilesReq)(nil),              // 26: pb.CopyFilesReq
	(*CopyFilesResp)(nil),             // 27: pb.CopyFilesResp
	(*SoftDeleteFilesReq)(nil),        // 28: pb.SoftDeleteFilesReq
	(*SoftDeleteFilesResp)(nil),       // 29: pb.SoftDeleteFilesResp
	(*ListTrashReq)(nil),              // 30: pb.ListTrashReq
	(*ListTrashResp)(nil),             // 31: pb.ListTrashResp
	(*RestoreFilesReq)(nil),           // 32: pb.RestoreFilesReq
	(*RestoreFilesResp)(nil),          // 33: pb.RestoreFilesResp
	(*HardDeleteFilesReq)(nil),        // 34: pb.HardDeleteFilesReq
	(*HardDeleteFilesResp)(nil),       // 35: pb.HardDeleteFilesResp
	(*ClearTrashReq)(nil),             // 36: pb.ClearTrashReq
	(*ClearTrashResp)(nil),            // 37: pb.ClearTrashResp
	(*CalcUserUsedSizeReq)(nil),       // 38: pb.CalcUserUsedSizeReq
	(*CalcUserUsedSizeResp)(nil),      // 39: pb.CalcUserUsedSizeResp
}
var file_app_file_cmd_rpc_pb_file_proto_depIdxs = []int32{
	1,  // 0: pb.CheckInstantUploadResp.meta:type_name -> pb.FileMeta
	0,  // 1: pb.GetFileInfoResp.file:type_name -> pb.FileInfo
	0,  // 2: pb.GetFilesByIdsResp.files:type_name -> pb.FileInfo
	0,  // 3: pb.ListFilesResp.list:type_name -> pb.FileInfo
	0,  // 4: pb.GetFilePathResp.path:type_name -> pb.FileInfo
	0,  // 5: pb.ListTrashResp.list:type_name -> pb.FileInfo
	2,  // 6: pb.FileService.CheckInstantUpload:input_type -> pb.CheckInstantUploadReq
	4,  // 7: pb.FileService.GetPresignedUploadUrl:input_type -> pb.GetPresignedUploadUrlReq
	6,  // 8: pb.FileService.CreateFile:input_type -> pb.CreateFileReq
	8,  // 9: pb.FileService.CreateFolder:input_type -> pb.CreateFolderReq
	10, // 10: pb.FileService.GetFileInfo:input_type -> pb.GetFileInfoReq
	12, // 11: pb.FileService.GetFilesByIds:input_type -> pb.GetFilesByIdsReq
	14, // 12: pb.FileService.CheckFileExists:input_type -> pb.CheckFileExistsReq
	16, // 13: pb.FileService.ListFiles:input_type -> pb.ListFilesReq
	18, // 14: pb.FileService.GetFilePath:input_type -> pb.GetFilePathReq
	20, // 15: pb.FileService.GetDownloadUrl:input_type -> pb.GetDownloadUrlReq
	22, // 16: pb.FileService.MoveFiles:input_type -> pb.MoveFilesReq
	24, // 17: pb.FileService.RenameFile:input_type -> pb.RenameFileReq
	26, // 18: pb.FileService.CopyFiles:input_type -> pb.CopyFilesReq
	28, // 19: pb.FileService.SoftDeleteFiles:input_type -> pb.SoftDeleteFilesReq
	30, // 20: pb.FileService.ListTrash:input_type -> pb.ListTrashReq
	32, // 21: pb.FileService.RestoreFiles:input_type -> pb.RestoreFilesReq
	34, // 22: pb.FileService.HardDeleteFiles:input_type -> pb.HardDeleteFilesReq
	36, // 23: pb.FileService.ClearTrash:input_type -> pb.ClearTrashReq
	38, // 24: pb.FileService.CalcUserUsedSize:input_type -> pb.CalcUserUsedSizeReq
	3,  // 25: pb.FileService.CheckInstantUpload:output_type -> pb.CheckInstantUploadResp
	5,  // 26: pb.FileService.GetPresignedUploadUrl:output_type -> pb.GetPresignedUploadUrlResp
	7,  // 27: pb.FileService.CreateFile:output_type -> pb.CreateFileResp
	9,  // 28: pb.FileService.CreateFolder:output_type -> pb.CreateFolderResp
	11, // 29: pb.FileService.GetFileInfo:output_type -> pb.GetFileInfoResp
	13, // 30: pb.FileService.GetFilesByIds:output_type -> pb.GetFilesByIdsResp
	15, // 31: pb.FileService.CheckFileExists:output_type -> pb.CheckFileExistsResp
	17, // 32: pb.FileService.ListFiles:output_type -> pb.ListFilesResp
	19, // 33: pb.FileService.GetFilePath:output_type -> pb.GetFilePathResp
	21, // 34: pb.FileService.GetDownloadUrl:output_type -> pb.GetDownloadUrlResp
	23, // 35: pb.FileService.MoveFiles:output_type -> pb.MoveFilesResp
	25, // 36: pb.FileService.RenameFile:output_type -> pb.RenameFileResp
	27, // 37: pb.FileService.CopyFiles:output_type -> pb.CopyFilesResp
	29, // 38: pb.FileService.SoftDeleteFiles:output_type -> pb.SoftDeleteFilesResp
	31, // 39: pb.FileService.ListTrash:output_type -> pb.ListTrashResp
	33, // 40: pb.FileService.RestoreFiles:output_type -> pb.RestoreFilesResp
	35, // 41: pb.FileService.HardDeleteFiles:output_type -> pb.HardDeleteFilesResp
	37, // 42: pb.FileService.ClearTrash:output_type -> pb.ClearTrashResp
	39, // 43: pb.FileService.CalcUserUsedSize:output_type -> pb.CalcUserUsedSizeResp
	25, // [25:44] is the sub-list for method output_type
	6,  // [6:25] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_file_cmd_rpc_pb_file_proto_init() }
func file_app_file_cmd_rpc_pb_file_proto_init() {
	if File_app_file_cmd_rpc_pb_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_file_cmd_rpc_pb_file_proto_rawDesc), len(file_app_file_cmd_rpc_pb_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_file_cmd_rpc_pb_file_proto_goTypes,
		DependencyIndexes: file_app_file_cmd_rpc_pb_file_proto_depIdxs,
		MessageInfos:      file_app_file_cmd_rpc_pb_file_proto_msgTypes,
	}.Build()
	File_app_file_cmd_rpc_pb_file_proto = out.File
	file_app_file_cmd_rpc_pb_file_proto_goTypes = nil
	file_app_file_cmd_rpc_pb_file_proto_depIdxs = nil
}
