// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: app/share/cmd/rpc/pb/share.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShareService_CreateShare_FullMethodName         = "/pb.ShareService/CreateShare"
	ShareService_GetShareList_FullMethodName        = "/pb.ShareService/GetShareList"
	ShareService_CancelShare_FullMethodName         = "/pb.ShareService/CancelShare"
	ShareService_UpdateShare_FullMethodName         = "/pb.ShareService/UpdateShare"
	ShareService_GetShareDetail_FullMethodName      = "/pb.ShareService/GetShareDetail"
	ShareService_GetShareDownloadUrl_FullMethodName = "/pb.ShareService/GetShareDownloadUrl"
	ShareService_SaveShare_FullMethodName           = "/pb.ShareService/SaveShare"
	ShareService_GetShareByIdentity_FullMethodName  = "/pb.ShareService/GetShareByIdentity"
	ShareService_IncrClickNum_FullMethodName        = "/pb.ShareService/IncrClickNum"
	ShareService_ValidateShare_FullMethodName       = "/pb.ShareService/ValidateShare"
)

// ShareServiceClient is the client API for ShareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShareServiceClient interface {
	// -------- 分享管理 --------
	// 创建分享
	CreateShare(ctx context.Context, in *CreateShareReq, opts ...grpc.CallOption) (*CreateShareResp, error)
	// 获取分享列表
	GetShareList(ctx context.Context, in *GetShareListReq, opts ...grpc.CallOption) (*GetShareListResp, error)
	// 取消分享
	CancelShare(ctx context.Context, in *CancelShareReq, opts ...grpc.CallOption) (*CancelShareResp, error)
	// 更新分享
	UpdateShare(ctx context.Context, in *UpdateShareReq, opts ...grpc.CallOption) (*UpdateShareResp, error)
	// -------- 分享访问 --------
	// 获取分享详情（验证提取码）
	GetShareDetail(ctx context.Context, in *GetShareDetailReq, opts ...grpc.CallOption) (*GetShareDetailResp, error)
	// 获取分享下载链接
	GetShareDownloadUrl(ctx context.Context, in *GetShareDownloadUrlReq, opts ...grpc.CallOption) (*GetShareDownloadUrlResp, error)
	// 保存分享到网盘
	SaveShare(ctx context.Context, in *SaveShareReq, opts ...grpc.CallOption) (*SaveShareResp, error)
	// -------- 内部方法 --------
	// 根据标识获取分享信息
	GetShareByIdentity(ctx context.Context, in *GetShareByIdentityReq, opts ...grpc.CallOption) (*GetShareByIdentityResp, error)
	// 增加点击次数
	IncrClickNum(ctx context.Context, in *IncrClickNumReq, opts ...grpc.CallOption) (*IncrClickNumResp, error)
	// 验证分享是否有效
	ValidateShare(ctx context.Context, in *ValidateShareReq, opts ...grpc.CallOption) (*ValidateShareResp, error)
}

type shareServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShareServiceClient(cc grpc.ClientConnInterface) ShareServiceClient {
	return &shareServiceClient{cc}
}

func (c *shareServiceClient) CreateShare(ctx context.Context, in *CreateShareReq, opts ...grpc.CallOption) (*CreateShareResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShareResp)
	err := c.cc.Invoke(ctx, ShareService_CreateShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetShareList(ctx context.Context, in *GetShareListReq, opts ...grpc.CallOption) (*GetShareListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShareListResp)
	err := c.cc.Invoke(ctx, ShareService_GetShareList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) CancelShare(ctx context.Context, in *CancelShareReq, opts ...grpc.CallOption) (*CancelShareResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelShareResp)
	err := c.cc.Invoke(ctx, ShareService_CancelShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) UpdateShare(ctx context.Context, in *UpdateShareReq, opts ...grpc.CallOption) (*UpdateShareResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateShareResp)
	err := c.cc.Invoke(ctx, ShareService_UpdateShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetShareDetail(ctx context.Context, in *GetShareDetailReq, opts ...grpc.CallOption) (*GetShareDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShareDetailResp)
	err := c.cc.Invoke(ctx, ShareService_GetShareDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetShareDownloadUrl(ctx context.Context, in *GetShareDownloadUrlReq, opts ...grpc.CallOption) (*GetShareDownloadUrlResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShareDownloadUrlResp)
	err := c.cc.Invoke(ctx, ShareService_GetShareDownloadUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) SaveShare(ctx context.Context, in *SaveShareReq, opts ...grpc.CallOption) (*SaveShareResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveShareResp)
	err := c.cc.Invoke(ctx, ShareService_SaveShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetShareByIdentity(ctx context.Context, in *GetShareByIdentityReq, opts ...grpc.CallOption) (*GetShareByIdentityResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShareByIdentityResp)
	err := c.cc.Invoke(ctx, ShareService_GetShareByIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) IncrClickNum(ctx context.Context, in *IncrClickNumReq, opts ...grpc.CallOption) (*IncrClickNumResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrClickNumResp)
	err := c.cc.Invoke(ctx, ShareService_IncrClickNum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) ValidateShare(ctx context.Context, in *ValidateShareReq, opts ...grpc.CallOption) (*ValidateShareResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateShareResp)
	err := c.cc.Invoke(ctx, ShareService_ValidateShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShareServiceServer is the server API for ShareService service.
// All implementations must embed UnimplementedShareServiceServer
// for forward compatibility.
type ShareServiceServer interface {
	// -------- 分享管理 --------
	// 创建分享
	CreateShare(context.Context, *CreateShareReq) (*CreateShareResp, error)
	// 获取分享列表
	GetShareList(context.Context, *GetShareListReq) (*GetShareListResp, error)
	// 取消分享
	CancelShare(context.Context, *CancelShareReq) (*CancelShareResp, error)
	// 更新分享
	UpdateShare(context.Context, *UpdateShareReq) (*UpdateShareResp, error)
	// -------- 分享访问 --------
	// 获取分享详情（验证提取码）
	GetShareDetail(context.Context, *GetShareDetailReq) (*GetShareDetailResp, error)
	// 获取分享下载链接
	GetShareDownloadUrl(context.Context, *GetShareDownloadUrlReq) (*GetShareDownloadUrlResp, error)
	// 保存分享到网盘
	SaveShare(context.Context, *SaveShareReq) (*SaveShareResp, error)
	// -------- 内部方法 --------
	// 根据标识获取分享信息
	GetShareByIdentity(context.Context, *GetShareByIdentityReq) (*GetShareByIdentityResp, error)
	// 增加点击次数
	IncrClickNum(context.Context, *IncrClickNumReq) (*IncrClickNumResp, error)
	// 验证分享是否有效
	ValidateShare(context.Context, *ValidateShareReq) (*ValidateShareResp, error)
	mustEmbedUnimplementedShareServiceServer()
}

// UnimplementedShareServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShareServiceServer struct{}

func (UnimplementedShareServiceServer) CreateShare(context.Context, *CreateShareReq) (*CreateShareResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShare not implemented")
}
func (UnimplementedShareServiceServer) GetShareList(context.Context, *GetShareListReq) (*GetShareListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShareList not implemented")
}
func (UnimplementedShareServiceServer) CancelShare(context.Context, *CancelShareReq) (*CancelShareResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelShare not implemented")
}
func (UnimplementedShareServiceServer) UpdateShare(context.Context, *UpdateShareReq) (*UpdateShareResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateShare not implemented")
}
func (UnimplementedShareServiceServer) GetShareDetail(context.Context, *GetShareDetailReq) (*GetShareDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShareDetail not implemented")
}
func (UnimplementedShareServiceServer) GetShareDownloadUrl(context.Context, *GetShareDownloadUrlReq) (*GetShareDownloadUrlResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShareDownloadUrl not implemented")
}
func (UnimplementedShareServiceServer) SaveShare(context.Context, *SaveShareReq) (*SaveShareResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveShare not implemented")
}
func (UnimplementedShareServiceServer) GetShareByIdentity(context.Context, *GetShareByIdentityReq) (*GetShareByIdentityResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShareByIdentity not implemented")
}
func (UnimplementedShareServiceServer) IncrClickNum(context.Context, *IncrClickNumReq) (*IncrClickNumResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrClickNum not implemented")
}
func (UnimplementedShareServiceServer) ValidateShare(context.Context, *ValidateShareReq) (*ValidateShareResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateShare not implemented")
}
func (UnimplementedShareServiceServer) mustEmbedUnimplementedShareServiceServer() {}
func (UnimplementedShareServiceServer) testEmbeddedByValue()                      {}

// UnsafeShareServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShareServiceServer will
// result in compilation errors.
type UnsafeShareServiceServer interface {
	mustEmbedUnimplementedShareServiceServer()
}

func RegisterShareServiceServer(s grpc.ServiceRegistrar, srv ShareServiceServer) {
	// If the following call panics, it indicates UnimplementedShareServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShareService_ServiceDesc, srv)
}

func _ShareService_CreateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).CreateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_CreateShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).CreateShare(ctx, req.(*CreateShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetShareList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShareListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetShareList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_GetShareList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetShareList(ctx, req.(*GetShareListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_CancelShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).CancelShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_CancelShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).CancelShare(ctx, req.(*CancelShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_UpdateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).UpdateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_UpdateShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).UpdateShare(ctx, req.(*UpdateShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetShareDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShareDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetShareDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_GetShareDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetShareDetail(ctx, req.(*GetShareDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetShareDownloadUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShareDownloadUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetShareDownloadUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_GetShareDownloadUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetShareDownloadUrl(ctx, req.(*GetShareDownloadUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_SaveShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).SaveShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_SaveShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).SaveShare(ctx, req.(*SaveShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetShareByIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShareByIdentityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetShareByIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_GetShareByIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetShareByIdentity(ctx, req.(*GetShareByIdentityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_IncrClickNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrClickNumReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).IncrClickNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_IncrClickNum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).IncrClickNum(ctx, req.(*IncrClickNumReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_ValidateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateShareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).ValidateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShareService_ValidateShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).ValidateShare(ctx, req.(*ValidateShareReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ShareService_ServiceDesc is the grpc.ServiceDesc for ShareService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShareService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ShareService",
	HandlerType: (*ShareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShare",
			Handler:    _ShareService_CreateShare_Handler,
		},
		{
			MethodName: "GetShareList",
			Handler:    _ShareService_GetShareList_Handler,
		},
		{
			MethodName: "CancelShare",
			Handler:    _ShareService_CancelShare_Handler,
		},
		{
			MethodName: "UpdateShare",
			Handler:    _ShareService_UpdateShare_Handler,
		},
		{
			MethodName: "GetShareDetail",
			Handler:    _ShareService_GetShareDetail_Handler,
		},
		{
			MethodName: "GetShareDownloadUrl",
			Handler:    _ShareService_GetShareDownloadUrl_Handler,
		},
		{
			MethodName: "SaveShare",
			Handler:    _ShareService_SaveShare_Handler,
		},
		{
			MethodName: "GetShareByIdentity",
			Handler:    _ShareService_GetShareByIdentity_Handler,
		},
		{
			MethodName: "IncrClickNum",
			Handler:    _ShareService_IncrClickNum_Handler,
		},
		{
			MethodName: "ValidateShare",
			Handler:    _ShareService_ValidateShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/share/cmd/rpc/pb/share.proto",
}
