// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: app/share/cmd/rpc/pb/share.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分享记录信息
type ShareInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Identity           string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`                     // 分享唯一标识
	UserId             int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`                        // 分享者ID
	RepositoryIdentity string                 `protobuf:"bytes,4,opt,name=repositoryIdentity,proto3" json:"repositoryIdentity,omitempty"` // 关联文件Identity
	Code               string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`                             // 提取码
	ClickNum           int64                  `protobuf:"varint,6,opt,name=clickNum,proto3" json:"clickNum,omitempty"`                    // 点击次数
	ExpiredTime        int64                  `protobuf:"varint,7,opt,name=expiredTime,proto3" json:"expiredTime,omitempty"`              // 失效时间戳（0=永久）
	Status             int64                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`                        // 状态 0:正常 1:已封禁
	CreateTime         int64                  `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime,omitempty"`                // 创建时间
	UpdateTime         int64                  `protobuf:"varint,10,opt,name=updateTime,proto3" json:"updateTime,omitempty"`               // 更新时间
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ShareInfo) Reset() {
	*x = ShareInfo{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareInfo) ProtoMessage() {}

func (x *ShareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareInfo.ProtoReflect.Descriptor instead.
func (*ShareInfo) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{0}
}

func (x *ShareInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShareInfo) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ShareInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ShareInfo) GetRepositoryIdentity() string {
	if x != nil {
		return x.RepositoryIdentity
	}
	return ""
}

func (x *ShareInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShareInfo) GetClickNum() int64 {
	if x != nil {
		return x.ClickNum
	}
	return 0
}

func (x *ShareInfo) GetExpiredTime() int64 {
	if x != nil {
		return x.ExpiredTime
	}
	return 0
}

func (x *ShareInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ShareInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ShareInfo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 分享文件信息（从file服务获取后组装）
type ShareFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ext           string                 `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,5,opt,name=isDir,proto3" json:"isDir,omitempty"`
	Hash          string                 `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`          // 文件hash（用于保存时判断秒传）
	ParentId      int64                  `protobuf:"varint,7,opt,name=parentId,proto3" json:"parentId,omitempty"` // 父目录ID（文件夹内文件需要）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareFileInfo) Reset() {
	*x = ShareFileInfo{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareFileInfo) ProtoMessage() {}

func (x *ShareFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareFileInfo.ProtoReflect.Descriptor instead.
func (*ShareFileInfo) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{1}
}

func (x *ShareFileInfo) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ShareFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShareFileInfo) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *ShareFileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ShareFileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *ShareFileInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ShareFileInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

// =====================================
// 创建分享
// =====================================
type CreateShareReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RepositoryIdentity string                 `protobuf:"bytes,2,opt,name=repositoryIdentity,proto3" json:"repositoryIdentity,omitempty"` // 文件Identity
	ExpiredType        int64                  `protobuf:"varint,3,opt,name=expiredType,proto3" json:"expiredType,omitempty"`              // 有效期类型: 0永久 1:1天 7:7天 30:30天
	HasCode            bool                   `protobuf:"varint,4,opt,name=hasCode,proto3" json:"hasCode,omitempty"`                      // 是否需要提取码
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateShareReq) Reset() {
	*x = CreateShareReq{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareReq) ProtoMessage() {}

func (x *CreateShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareReq.ProtoReflect.Descriptor instead.
func (*CreateShareReq) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShareReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateShareReq) GetRepositoryIdentity() string {
	if x != nil {
		return x.RepositoryIdentity
	}
	return ""
}

func (x *CreateShareReq) GetExpiredType() int64 {
	if x != nil {
		return x.ExpiredType
	}
	return 0
}

func (x *CreateShareReq) GetHasCode() bool {
	if x != nil {
		return x.HasCode
	}
	return false
}

type CreateShareResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"` // 分享标识
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`         // 提取码（如果设置了）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShareResp) Reset() {
	*x = CreateShareResp{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShareResp) ProtoMessage() {}

func (x *CreateShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShareResp.ProtoReflect.Descriptor instead.
func (*CreateShareResp) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShareResp) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *CreateShareResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// =====================================
// 获取分享列表
// =====================================
type GetShareListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareListReq) Reset() {
	*x = GetShareListReq{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareListReq) ProtoMessage() {}

func (x *GetShareListReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareListReq.ProtoReflect.Descriptor instead.
func (*GetShareListReq) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{4}
}

func (x *GetShareListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetShareListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetShareListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetShareListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ShareInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareListResp) Reset() {
	*x = GetShareListResp{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareListResp) ProtoMessage() {}

func (x *GetShareListResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareListResp.ProtoReflect.Descriptor instead.
func (*GetShareListResp) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{5}
}

func (x *GetShareListResp) GetList() []*ShareInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetShareListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// =====================================
// 取消分享
// =====================================
type CancelShareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Identities    []string               `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"` // 分享标识列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShareReq) Reset() {
	*x = CancelShareReq{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShareReq) ProtoMessage() {}

func (x *CancelShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShareReq.ProtoReflect.Descriptor instead.
func (*CancelShareReq) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{6}
}

func (x *CancelShareReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelShareReq) GetIdentities() []string {
	if x != nil {
		return x.Identities
	}
	return nil
}

type CancelShareResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CancelledCount int64                  `protobuf:"varint,1,opt,name=cancelledCount,proto3" json:"cancelledCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelShareResp) Reset() {
	*x = CancelShareResp{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShareResp) ProtoMessage() {}

func (x *CancelShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShareResp.ProtoReflect.Descriptor instead.
func (*CancelShareResp) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{7}
}

func (x *CancelShareResp) GetCancelledCount() int64 {
	if x != nil {
		return x.CancelledCount
	}
	return 0
}

// =====================================
// 更新分享
// =====================================
type UpdateShareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`        // 分享标识
	ExpiredType   int64                  `protobuf:"varint,3,opt,name=expiredType,proto3" json:"expiredType,omitempty"` // 新的有效期类型（-1表示不修改）
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`                // 新的提取码（空字符串=取消提取码，-1表示不修改）
	UpdateCode    bool                   `protobuf:"varint,5,opt,name=updateCode,proto3" json:"updateCode,omitempty"`   // 是否更新提取码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShareReq) Reset() {
	*x = UpdateShareReq{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShareReq) ProtoMessage() {}

func (x *UpdateShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShareReq.ProtoReflect.Descriptor instead.
func (*UpdateShareReq) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateShareReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateShareReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *UpdateShareReq) GetExpiredType() int64 {
	if x != nil {
		return x.ExpiredType
	}
	return 0
}

func (x *UpdateShareReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateShareReq) GetUpdateCode() bool {
	if x != nil {
		return x.UpdateCode
	}
	return false
}

type UpdateShareResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShareResp) Reset() {
	*x = UpdateShareResp{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShareResp) ProtoMessage() {}

func (x *UpdateShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShareResp.ProtoReflect.Descriptor instead.
func (*UpdateShareResp) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{9}
}

// =====================================
// 获取分享详情（验证提取码）
// =====================================
type GetShareDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"` // 分享标识
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`         // 提取码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareDetailReq) Reset() {
	*x = GetShareDetailReq{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareDetailReq) ProtoMessage() {}

func (x *GetShareDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareDetailReq.ProtoReflect.Descriptor instead.
func (*GetShareDetailReq) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{10}
}

func (x *GetShareDetailReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetShareDetailReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetShareDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         *ShareInfo             `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`           // 分享信息
	File          *ShareFileInfo         `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`             // 分享的文件信息
	SharerName    string                 `protobuf:"bytes,3,opt,name=sharerName,proto3" json:"sharerName,omitempty"` // 分享者名称
	Children      []*ShareFileInfo       `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`     // 如果是文件夹，包含子文件列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareDetailResp) Reset() {
	*x = GetShareDetailResp{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareDetailResp) ProtoMessage() {}

func (x *GetShareDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareDetailResp.ProtoReflect.Descriptor instead.
func (*GetShareDetailResp) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{11}
}

func (x *GetShareDetailResp) GetShare() *ShareInfo {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *GetShareDetailResp) GetFile() *ShareFileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *GetShareDetailResp) GetSharerName() string {
	if x != nil {
		return x.SharerName
	}
	return ""
}

func (x *GetShareDetailResp) GetChildren() []*ShareFileInfo {
	if x != nil {
		return x.Children
	}
	return nil
}

// =====================================
// 获取分享下载链接
// =====================================
type GetShareDownloadUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`         // 分享标识
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                 // 提取码
	FileIdentity  string                 `protobuf:"bytes,3,opt,name=fileIdentity,proto3" json:"fileIdentity,omitempty"` // 要下载的文件Identity（文件夹分享时需要指定）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareDownloadUrlReq) Reset() {
	*x = GetShareDownloadUrlReq{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareDownloadUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareDownloadUrlReq) ProtoMessage() {}

func (x *GetShareDownloadUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareDownloadUrlReq.ProtoReflect.Descriptor instead.
func (*GetShareDownloadUrlReq) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{12}
}

func (x *GetShareDownloadUrlReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetShareDownloadUrlReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetShareDownloadUrlReq) GetFileIdentity() string {
	if x != nil {
		return x.FileIdentity
	}
	return ""
}

type GetShareDownloadUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // 下载链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareDownloadUrlResp) Reset() {
	*x = GetShareDownloadUrlResp{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareDownloadUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareDownloadUrlResp) ProtoMessage() {}

func (x *GetShareDownloadUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareDownloadUrlResp.ProtoReflect.Descriptor instead.
func (*GetShareDownloadUrlResp) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{13}
}

func (x *GetShareDownloadUrlResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// =====================================
// 保存分享到网盘
// =====================================
type SaveShareReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`                 // 保存者ID
	Identity       string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`              // 分享标识
	Code           string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                      // 提取码
	FileIdentities []string               `protobuf:"bytes,4,rep,name=fileIdentities,proto3" json:"fileIdentities,omitempty"`  // 要保存的文件Identity列表
	TargetFolderId int64                  `protobuf:"varint,5,opt,name=targetFolderId,proto3" json:"targetFolderId,omitempty"` // 目标文件夹ID（0=根目录）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SaveShareReq) Reset() {
	*x = SaveShareReq{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveShareReq) ProtoMessage() {}

func (x *SaveShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveShareReq.ProtoReflect.Descriptor instead.
func (*SaveShareReq) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{14}
}

func (x *SaveShareReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveShareReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *SaveShareReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SaveShareReq) GetFileIdentities() []string {
	if x != nil {
		return x.FileIdentities
	}
	return nil
}

func (x *SaveShareReq) GetTargetFolderId() int64 {
	if x != nil {
		return x.TargetFolderId
	}
	return 0
}

type SaveShareResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavedCount    int64                  `protobuf:"varint,1,opt,name=savedCount,proto3" json:"savedCount,omitempty"` // 保存成功的文件数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveShareResp) Reset() {
	*x = SaveShareResp{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveShareResp) ProtoMessage() {}

func (x *SaveShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveShareResp.ProtoReflect.Descriptor instead.
func (*SaveShareResp) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{15}
}

func (x *SaveShareResp) GetSavedCount() int64 {
	if x != nil {
		return x.SavedCount
	}
	return 0
}

// 根据分享标识获取分享信息（供其他服务调用）
type GetShareByIdentityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareByIdentityReq) Reset() {
	*x = GetShareByIdentityReq{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareByIdentityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareByIdentityReq) ProtoMessage() {}

func (x *GetShareByIdentityReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareByIdentityReq.ProtoReflect.Descriptor instead.
func (*GetShareByIdentityReq) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{16}
}

func (x *GetShareByIdentityReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type GetShareByIdentityResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Share         *ShareInfo             `protobuf:"bytes,1,opt,name=share,proto3" json:"share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShareByIdentityResp) Reset() {
	*x = GetShareByIdentityResp{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShareByIdentityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShareByIdentityResp) ProtoMessage() {}

func (x *GetShareByIdentityResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShareByIdentityResp.ProtoReflect.Descriptor instead.
func (*GetShareByIdentityResp) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{17}
}

func (x *GetShareByIdentityResp) GetShare() *ShareInfo {
	if x != nil {
		return x.Share
	}
	return nil
}

// 增加点击次数
type IncrClickNumReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrClickNumReq) Reset() {
	*x = IncrClickNumReq{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrClickNumReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrClickNumReq) ProtoMessage() {}

func (x *IncrClickNumReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrClickNumReq.ProtoReflect.Descriptor instead.
func (*IncrClickNumReq) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{18}
}

func (x *IncrClickNumReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type IncrClickNumResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrClickNumResp) Reset() {
	*x = IncrClickNumResp{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrClickNumResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrClickNumResp) ProtoMessage() {}

func (x *IncrClickNumResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrClickNumResp.ProtoReflect.Descriptor instead.
func (*IncrClickNumResp) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{19}
}

// 验证分享是否有效（检查过期、状态等）
type ValidateShareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateShareReq) Reset() {
	*x = ValidateShareReq{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateShareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateShareReq) ProtoMessage() {}

func (x *ValidateShareReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateShareReq.ProtoReflect.Descriptor instead.
func (*ValidateShareReq) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{20}
}

func (x *ValidateShareReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ValidateShareReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ValidateShareResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 无效原因
	Share         *ShareInfo             `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`   // 有效时返回分享信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateShareResp) Reset() {
	*x = ValidateShareResp{}
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateShareResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateShareResp) ProtoMessage() {}

func (x *ValidateShareResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_share_cmd_rpc_pb_share_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateShareResp.ProtoReflect.Descriptor instead.
func (*ValidateShareResp) Descriptor() ([]byte, []int) {
	return file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP(), []int{21}
}

func (x *ValidateShareResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateShareResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ValidateShareResp) GetShare() *ShareInfo {
	if x != nil {
		return x.Share
	}
	return nil
}

var File_app_share_cmd_rpc_pb_share_proto protoreflect.FileDescriptor

const file_app_share_cmd_rpc_pb_share_proto_rawDesc = "" +
	"\n" +
	" app/share/cmd/rpc/pb/share.proto\x12\x02pb\"\xa9\x02\n" +
	"\tShareInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12.\n" +
	"\x12repositoryIdentity\x18\x04 \x01(\tR\x12repositoryIdentity\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x1a\n" +
	"\bclickNum\x18\x06 \x01(\x03R\bclickNum\x12 \n" +
	"\vexpiredTime\x18\a \x01(\x03R\vexpiredTime\x12\x16\n" +
	"\x06status\x18\b \x01(\x03R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\n" +
	" \x01(\x03R\n" +
	"updateTime\"\xab\x01\n" +
	"\rShareFileInfo\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03ext\x18\x03 \x01(\tR\x03ext\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x14\n" +
	"\x05isDir\x18\x05 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\tR\x04hash\x12\x1a\n" +
	"\bparentId\x18\a \x01(\x03R\bparentId\"\x94\x01\n" +
	"\x0eCreateShareReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12.\n" +
	"\x12repositoryIdentity\x18\x02 \x01(\tR\x12repositoryIdentity\x12 \n" +
	"\vexpiredType\x18\x03 \x01(\x03R\vexpiredType\x12\x18\n" +
	"\ahasCode\x18\x04 \x01(\bR\ahasCode\"A\n" +
	"\x0fCreateShareResp\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"Y\n" +
	"\x0fGetShareListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\"K\n" +
	"\x10GetShareListResp\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.pb.ShareInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"H\n" +
	"\x0eCancelShareReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"identities\x18\x02 \x03(\tR\n" +
	"identities\"9\n" +
	"\x0fCancelShareResp\x12&\n" +
	"\x0ecancelledCount\x18\x01 \x01(\x03R\x0ecancelledCount\"\x9a\x01\n" +
	"\x0eUpdateShareReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12 \n" +
	"\vexpiredType\x18\x03 \x01(\x03R\vexpiredType\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"updateCode\x18\x05 \x01(\bR\n" +
	"updateCode\"\x11\n" +
	"\x0fUpdateShareResp\"C\n" +
	"\x11GetShareDetailReq\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\xaf\x01\n" +
	"\x12GetShareDetailResp\x12#\n" +
	"\x05share\x18\x01 \x01(\v2\r.pb.ShareInfoR\x05share\x12%\n" +
	"\x04file\x18\x02 \x01(\v2\x11.pb.ShareFileInfoR\x04file\x12\x1e\n" +
	"\n" +
	"sharerName\x18\x03 \x01(\tR\n" +
	"sharerName\x12-\n" +
	"\bchildren\x18\x04 \x03(\v2\x11.pb.ShareFileInfoR\bchildren\"l\n" +
	"\x16GetShareDownloadUrlReq\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\"\n" +
	"\ffileIdentity\x18\x03 \x01(\tR\ffileIdentity\"+\n" +
	"\x17GetShareDownloadUrlResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xa6\x01\n" +
	"\fSaveShareReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12&\n" +
	"\x0efileIdentities\x18\x04 \x03(\tR\x0efileIdentities\x12&\n" +
	"\x0etargetFolderId\x18\x05 \x01(\x03R\x0etargetFolderId\"/\n" +
	"\rSaveShareResp\x12\x1e\n" +
	"\n" +
	"savedCount\x18\x01 \x01(\x03R\n" +
	"savedCount\"3\n" +
	"\x15GetShareByIdentityReq\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"=\n" +
	"\x16GetShareByIdentityResp\x12#\n" +
	"\x05share\x18\x01 \x01(\v2\r.pb.ShareInfoR\x05share\"-\n" +
	"\x0fIncrClickNumReq\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"\x12\n" +
	"\x10IncrClickNumResp\"B\n" +
	"\x10ValidateShareReq\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"f\n" +
	"\x11ValidateShareResp\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12#\n" +
	"\x05share\x18\x03 \x01(\v2\r.pb.ShareInfoR\x05share2\xfa\x04\n" +
	"\fShareService\x126\n" +
	"\vCreateShare\x12\x12.pb.CreateShareReq\x1a\x13.pb.CreateShareResp\x129\n" +
	"\fGetShareList\x12\x13.pb.GetShareListReq\x1a\x14.pb.GetShareListResp\x126\n" +
	"\vCancelShare\x12\x12.pb.CancelShareReq\x1a\x13.pb.CancelShareResp\x126\n" +
	"\vUpdateShare\x12\x12.pb.UpdateShareReq\x1a\x13.pb.UpdateShareResp\x12?\n" +
	"\x0eGetShareDetail\x12\x15.pb.GetShareDetailReq\x1a\x16.pb.GetShareDetailResp\x12N\n" +
	"\x13GetShareDownloadUrl\x12\x1a.pb.GetShareDownloadUrlReq\x1a\x1b.pb.GetShareDownloadUrlResp\x120\n" +
	"\tSaveShare\x12\x10.pb.SaveShareReq\x1a\x11.pb.SaveShareResp\x12K\n" +
	"\x12GetShareByIdentity\x12\x19.pb.GetShareByIdentityReq\x1a\x1a.pb.GetShareByIdentityResp\x129\n" +
	"\fIncrClickNum\x12\x13.pb.IncrClickNumReq\x1a\x14.pb.IncrClickNumResp\x12<\n" +
	"\rValidateShare\x12\x14.pb.ValidateShareReq\x1a\x15.pb.ValidateShareRespB\x06Z\x04./pbb\x06proto3"

var (
	file_app_share_cmd_rpc_pb_share_proto_rawDescOnce sync.Once
	file_app_share_cmd_rpc_pb_share_proto_rawDescData []byte
)

func file_app_share_cmd_rpc_pb_share_proto_rawDescGZIP() []byte {
	file_app_share_cmd_rpc_pb_share_proto_rawDescOnce.Do(func() {
		file_app_share_cmd_rpc_pb_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_share_cmd_rpc_pb_share_proto_rawDesc), len(file_app_share_cmd_rpc_pb_share_proto_rawDesc)))
	})
	return file_app_share_cmd_rpc_pb_share_proto_rawDescData
}

var file_app_share_cmd_rpc_pb_share_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_app_share_cmd_rpc_pb_share_proto_goTypes = []any{
	(*ShareInfo)(nil),               // 0: pb.ShareInfo
	(*ShareFileInfo)(nil),           // 1: pb.ShareFileInfo
	(*CreateShareReq)(nil),          // 2: pb.CreateShareReq
	(*CreateShareResp)(nil),         // 3: pb.CreateShareResp
	(*GetShareListReq)(nil),         // 4: pb.GetShareListReq
	(*GetShareListResp)(nil),        // 5: pb.GetShareListResp
	(*CancelShareReq)(nil),          // 6: pb.CancelShareReq
	(*CancelShareResp)(nil),         // 7: pb.CancelShareResp
	(*UpdateShareReq)(nil),          // 8: pb.UpdateShareReq
	(*UpdateShareResp)(nil),         // 9: pb.UpdateShareResp
	(*GetShareDetailReq)(nil),       // 10: pb.GetShareDetailReq
	(*GetShareDetailResp)(nil),      // 11: pb.GetShareDetailResp
	(*GetShareDownloadUrlReq)(nil),  // 12: pb.GetShareDownloadUrlReq
	(*GetShareDownloadUrlResp)(nil), // 13: pb.GetShareDownloadUrlResp
	(*SaveShareReq)(nil),            // 14: pb.SaveShareReq
	(*SaveShareResp)(nil),           // 15: pb.SaveShareResp
	(*GetShareByIdentityReq)(nil),   // 16: pb.GetShareByIdentityReq
	(*GetShareByIdentityResp)(nil),  // 17: pb.GetShareByIdentityResp
	(*IncrClickNumReq)(nil),         // 18: pb.IncrClickNumReq
	(*IncrClickNumResp)(nil),        // 19: pb.IncrClickNumResp
	(*ValidateShareReq)(nil),        // 20: pb.ValidateShareReq
	(*ValidateShareResp)(nil),       // 21: pb.ValidateShareResp
}
var file_app_share_cmd_rpc_pb_share_proto_depIdxs = []int32{
	0,  // 0: pb.GetShareListResp.list:type_name -> pb.ShareInfo
	0,  // 1: pb.GetShareDetailResp.share:type_name -> pb.ShareInfo
	1,  // 2: pb.GetShareDetailResp.file:type_name -> pb.ShareFileInfo
	1,  // 3: pb.GetShareDetailResp.children:type_name -> pb.ShareFileInfo
	0,  // 4: pb.GetShareByIdentityResp.share:type_name -> pb.ShareInfo
	0,  // 5: pb.ValidateShareResp.share:type_name -> pb.ShareInfo
	2,  // 6: pb.ShareService.CreateShare:input_type -> pb.CreateShareReq
	4,  // 7: pb.ShareService.GetShareList:input_type -> pb.GetShareListReq
	6,  // 8: pb.ShareService.CancelShare:input_type -> pb.CancelShareReq
	8,  // 9: pb.ShareService.UpdateShare:input_type -> pb.UpdateShareReq
	10, // 10: pb.ShareService.GetShareDetail:input_type -> pb.GetShareDetailReq
	12, // 11: pb.ShareService.GetShareDownloadUrl:input_type -> pb.GetShareDownloadUrlReq
	14, // 12: pb.ShareService.SaveShare:input_type -> pb.SaveShareReq
	16, // 13: pb.ShareService.GetShareByIdentity:input_type -> pb.GetShareByIdentityReq
	18, // 14: pb.ShareService.IncrClickNum:input_type -> pb.IncrClickNumReq
	20, // 15: pb.ShareService.ValidateShare:input_type -> pb.ValidateShareReq
	3,  // 16: pb.ShareService.CreateShare:output_type -> pb.CreateShareResp
	5,  // 17: pb.ShareService.GetShareList:output_type -> pb.GetShareListResp
	7,  // 18: pb.ShareService.CancelShare:output_type -> pb.CancelShareResp
	9,  // 19: pb.ShareService.UpdateShare:output_type -> pb.UpdateShareResp
	11, // 20: pb.ShareService.GetShareDetail:output_type -> pb.GetShareDetailResp
	13, // 21: pb.ShareService.GetShareDownloadUrl:output_type -> pb.GetShareDownloadUrlResp
	15, // 22: pb.ShareService.SaveShare:output_type -> pb.SaveShareResp
	17, // 23: pb.ShareService.GetShareByIdentity:output_type -> pb.GetShareByIdentityResp
	19, // 24: pb.ShareService.IncrClickNum:output_type -> pb.IncrClickNumResp
	21, // 25: pb.ShareService.ValidateShare:output_type -> pb.ValidateShareResp
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_share_cmd_rpc_pb_share_proto_init() }
func file_app_share_cmd_rpc_pb_share_proto_init() {
	if File_app_share_cmd_rpc_pb_share_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_share_cmd_rpc_pb_share_proto_rawDesc), len(file_app_share_cmd_rpc_pb_share_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_share_cmd_rpc_pb_share_proto_goTypes,
		DependencyIndexes: file_app_share_cmd_rpc_pb_share_proto_depIdxs,
		MessageInfos:      file_app_share_cmd_rpc_pb_share_proto_msgTypes,
	}.Build()
	File_app_share_cmd_rpc_pb_share_proto = out.File
	file_app_share_cmd_rpc_pb_share_proto_goTypes = nil
	file_app_share_cmd_rpc_pb_share_proto_depIdxs = nil
}
