// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pb/search.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 搜索结果中的文件信息
type FileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // 文件 identity
	FileId        int64                  `protobuf:"varint,2,opt,name=fileId,proto3" json:"fileId,omitempty"`          // MySQL file_id
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`          // 用户ID
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`               // 文件名
	Ext           string                 `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`                 // 扩展名
	Size          uint64                 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`              // 文件大小
	IsDir         bool                   `protobuf:"varint,7,opt,name=isDir,proto3" json:"isDir,omitempty"`            // 是否为文件夹
	ParentId      int64                  `protobuf:"varint,8,opt,name=parentId,proto3" json:"parentId,omitempty"`      // 父目录ID
	Hash          string                 `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`               // 文件哈希
	CreateTime    int64                  `protobuf:"varint,10,opt,name=createTime,proto3" json:"createTime,omitempty"` // 创建时间
	UpdateTime    int64                  `protobuf:"varint,11,opt,name=updateTime,proto3" json:"updateTime,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileItem) Reset() {
	*x = FileItem{}
	mi := &file_pb_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileItem) ProtoMessage() {}

func (x *FileItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileItem.ProtoReflect.Descriptor instead.
func (*FileItem) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{0}
}

func (x *FileItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileItem) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *FileItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FileItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileItem) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *FileItem) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileItem) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *FileItem) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FileItem) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 搜索文件请求
type SearchFilesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`      // 用户ID
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`     // 搜索关键词
	Ext           []string               `protobuf:"bytes,3,rep,name=ext,proto3" json:"ext,omitempty"`             // 文件扩展名过滤
	IsDir         int64                  `protobuf:"varint,4,opt,name=isDir,proto3" json:"isDir,omitempty"`        // -1:全部 0:文件 1:文件夹
	MinSize       uint64                 `protobuf:"varint,5,opt,name=minSize,proto3" json:"minSize,omitempty"`    // 最小文件大小
	MaxSize       uint64                 `protobuf:"varint,6,opt,name=maxSize,proto3" json:"maxSize,omitempty"`    // 最大文件大小
	Page          int64                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`          // 页码
	PageSize      int64                  `protobuf:"varint,8,opt,name=pageSize,proto3" json:"pageSize,omitempty"`  // 每页数量
	SortBy        string                 `protobuf:"bytes,9,opt,name=sortBy,proto3" json:"sortBy,omitempty"`       // 排序字段
	SortDesc      bool                   `protobuf:"varint,10,opt,name=sortDesc,proto3" json:"sortDesc,omitempty"` // 是否降序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilesReq) Reset() {
	*x = SearchFilesReq{}
	mi := &file_pb_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilesReq) ProtoMessage() {}

func (x *SearchFilesReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilesReq.ProtoReflect.Descriptor instead.
func (*SearchFilesReq) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchFilesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchFilesReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchFilesReq) GetExt() []string {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *SearchFilesReq) GetIsDir() int64 {
	if x != nil {
		return x.IsDir
	}
	return 0
}

func (x *SearchFilesReq) GetMinSize() uint64 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

func (x *SearchFilesReq) GetMaxSize() uint64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *SearchFilesReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchFilesReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchFilesReq) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *SearchFilesReq) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

// 搜索文件响应
type SearchFilesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 总数
	List          []*FileItem            `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`    // 文件列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilesResp) Reset() {
	*x = SearchFilesResp{}
	mi := &file_pb_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilesResp) ProtoMessage() {}

func (x *SearchFilesResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilesResp.ProtoReflect.Descriptor instead.
func (*SearchFilesResp) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchFilesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchFilesResp) GetList() []*FileItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 索引文件请求（上传完成后调用）
type IndexFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`              // 文件 identity
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`     // 用户ID
	FileId        int64                  `protobuf:"varint,3,opt,name=fileId,proto3" json:"fileId,omitempty"`     // MySQL file_id
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`          // 文件名
	Ext           string                 `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`            // 扩展名
	Size          uint64                 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`         // 文件大小
	Hash          string                 `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"`          // 文件哈希
	ParentId      int64                  `protobuf:"varint,8,opt,name=parentId,proto3" json:"parentId,omitempty"` // 父目录ID
	IsDir         bool                   `protobuf:"varint,9,opt,name=isDir,proto3" json:"isDir,omitempty"`       // 是否为文件夹
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexFileReq) Reset() {
	*x = IndexFileReq{}
	mi := &file_pb_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexFileReq) ProtoMessage() {}

func (x *IndexFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexFileReq.ProtoReflect.Descriptor instead.
func (*IndexFileReq) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{3}
}

func (x *IndexFileReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IndexFileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IndexFileReq) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *IndexFileReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexFileReq) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *IndexFileReq) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IndexFileReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *IndexFileReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *IndexFileReq) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type IndexFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexFileResp) Reset() {
	*x = IndexFileResp{}
	mi := &file_pb_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexFileResp) ProtoMessage() {}

func (x *IndexFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexFileResp.ProtoReflect.Descriptor instead.
func (*IndexFileResp) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{4}
}

// 更新文件索引请求
type UpdateFileIndexReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // 文件 identity
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                      // 新文件名（空字符串表示不更新）
	ParentId       int64                  `protobuf:"varint,3,opt,name=parentId,proto3" json:"parentId,omitempty"`             // 新父目录ID（0 表示根目录）
	UpdateParentId bool                   `protobuf:"varint,4,opt,name=updateParentId,proto3" json:"updateParentId,omitempty"` // 是否更新 parentId（用于区分 "不更新" 和 "更新为0"）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateFileIndexReq) Reset() {
	*x = UpdateFileIndexReq{}
	mi := &file_pb_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileIndexReq) ProtoMessage() {}

func (x *UpdateFileIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileIndexReq.ProtoReflect.Descriptor instead.
func (*UpdateFileIndexReq) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFileIndexReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFileIndexReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFileIndexReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UpdateFileIndexReq) GetUpdateParentId() bool {
	if x != nil {
		return x.UpdateParentId
	}
	return false
}

type UpdateFileIndexResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileIndexResp) Reset() {
	*x = UpdateFileIndexResp{}
	mi := &file_pb_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileIndexResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileIndexResp) ProtoMessage() {}

func (x *UpdateFileIndexResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileIndexResp.ProtoReflect.Descriptor instead.
func (*UpdateFileIndexResp) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{6}
}

// 删除文件索引请求
type DeleteFileIndexReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 文件 identity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileIndexReq) Reset() {
	*x = DeleteFileIndexReq{}
	mi := &file_pb_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileIndexReq) ProtoMessage() {}

func (x *DeleteFileIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileIndexReq.ProtoReflect.Descriptor instead.
func (*DeleteFileIndexReq) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFileIndexReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFileIndexResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileIndexResp) Reset() {
	*x = DeleteFileIndexResp{}
	mi := &file_pb_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileIndexResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileIndexResp) ProtoMessage() {}

func (x *DeleteFileIndexResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileIndexResp.ProtoReflect.Descriptor instead.
func (*DeleteFileIndexResp) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{8}
}

// 获取用户文件统计
type GetUserStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsReq) Reset() {
	*x = GetUserStatsReq{}
	mi := &file_pb_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsReq) ProtoMessage() {}

func (x *GetUserStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsReq.ProtoReflect.Descriptor instead.
func (*GetUserStatsReq) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserStatsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalFiles    int64                  `protobuf:"varint,1,opt,name=totalFiles,proto3" json:"totalFiles,omitempty"`     // 文件总数
	TotalFolders  int64                  `protobuf:"varint,2,opt,name=totalFolders,proto3" json:"totalFolders,omitempty"` // 文件夹总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsResp) Reset() {
	*x = GetUserStatsResp{}
	mi := &file_pb_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsResp) ProtoMessage() {}

func (x *GetUserStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsResp.ProtoReflect.Descriptor instead.
func (*GetUserStatsResp) Descriptor() ([]byte, []int) {
	return file_pb_search_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserStatsResp) GetTotalFiles() int64 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

func (x *GetUserStatsResp) GetTotalFolders() int64 {
	if x != nil {
		return x.TotalFolders
	}
	return 0
}

var File_pb_search_proto protoreflect.FileDescriptor

const file_pb_search_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/search.proto\x12\x02pb\"\x8a\x02\n" +
	"\bFileItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06fileId\x18\x02 \x01(\x03R\x06fileId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03ext\x18\x05 \x01(\tR\x03ext\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x04R\x04size\x12\x14\n" +
	"\x05isDir\x18\a \x01(\bR\x05isDir\x12\x1a\n" +
	"\bparentId\x18\b \x01(\x03R\bparentId\x12\x12\n" +
	"\x04hash\x18\t \x01(\tR\x04hash\x12\x1e\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\v \x01(\x03R\n" +
	"updateTime\"\x82\x02\n" +
	"\x0eSearchFilesReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x10\n" +
	"\x03ext\x18\x03 \x03(\tR\x03ext\x12\x14\n" +
	"\x05isDir\x18\x04 \x01(\x03R\x05isDir\x12\x18\n" +
	"\aminSize\x18\x05 \x01(\x04R\aminSize\x12\x18\n" +
	"\amaxSize\x18\x06 \x01(\x04R\amaxSize\x12\x12\n" +
	"\x04page\x18\a \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\b \x01(\x03R\bpageSize\x12\x16\n" +
	"\x06sortBy\x18\t \x01(\tR\x06sortBy\x12\x1a\n" +
	"\bsortDesc\x18\n" +
	" \x01(\bR\bsortDesc\"I\n" +
	"\x0fSearchFilesResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12 \n" +
	"\x04list\x18\x02 \x03(\v2\f.pb.FileItemR\x04list\"\xce\x01\n" +
	"\fIndexFileReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06fileId\x18\x03 \x01(\x03R\x06fileId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03ext\x18\x05 \x01(\tR\x03ext\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x04R\x04size\x12\x12\n" +
	"\x04hash\x18\a \x01(\tR\x04hash\x12\x1a\n" +
	"\bparentId\x18\b \x01(\x03R\bparentId\x12\x14\n" +
	"\x05isDir\x18\t \x01(\bR\x05isDir\"\x0f\n" +
	"\rIndexFileResp\"|\n" +
	"\x12UpdateFileIndexReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bparentId\x18\x03 \x01(\x03R\bparentId\x12&\n" +
	"\x0eupdateParentId\x18\x04 \x01(\bR\x0eupdateParentId\"\x15\n" +
	"\x13UpdateFileIndexResp\"$\n" +
	"\x12DeleteFileIndexReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteFileIndexResp\")\n" +
	"\x0fGetUserStatsReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"V\n" +
	"\x10GetUserStatsResp\x12\x1e\n" +
	"\n" +
	"totalFiles\x18\x01 \x01(\x03R\n" +
	"totalFiles\x12\"\n" +
	"\ftotalFolders\x18\x02 \x01(\x03R\ftotalFolders2\xbc\x02\n" +
	"\rSearchService\x126\n" +
	"\vSearchFiles\x12\x12.pb.SearchFilesReq\x1a\x13.pb.SearchFilesResp\x129\n" +
	"\fGetUserStats\x12\x13.pb.GetUserStatsReq\x1a\x14.pb.GetUserStatsResp\x120\n" +
	"\tIndexFile\x12\x10.pb.IndexFileReq\x1a\x11.pb.IndexFileResp\x12B\n" +
	"\x0fUpdateFileIndex\x12\x16.pb.UpdateFileIndexReq\x1a\x17.pb.UpdateFileIndexResp\x12B\n" +
	"\x0fDeleteFileIndex\x12\x16.pb.DeleteFileIndexReq\x1a\x17.pb.DeleteFileIndexRespB\x06Z\x04./pbb\x06proto3"

var (
	file_pb_search_proto_rawDescOnce sync.Once
	file_pb_search_proto_rawDescData []byte
)

func file_pb_search_proto_rawDescGZIP() []byte {
	file_pb_search_proto_rawDescOnce.Do(func() {
		file_pb_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_search_proto_rawDesc), len(file_pb_search_proto_rawDesc)))
	})
	return file_pb_search_proto_rawDescData
}

var file_pb_search_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pb_search_proto_goTypes = []any{
	(*FileItem)(nil),            // 0: pb.FileItem
	(*SearchFilesReq)(nil),      // 1: pb.SearchFilesReq
	(*SearchFilesResp)(nil),     // 2: pb.SearchFilesResp
	(*IndexFileReq)(nil),        // 3: pb.IndexFileReq
	(*IndexFileResp)(nil),       // 4: pb.IndexFileResp
	(*UpdateFileIndexReq)(nil),  // 5: pb.UpdateFileIndexReq
	(*UpdateFileIndexResp)(nil), // 6: pb.UpdateFileIndexResp
	(*DeleteFileIndexReq)(nil),  // 7: pb.DeleteFileIndexReq
	(*DeleteFileIndexResp)(nil), // 8: pb.DeleteFileIndexResp
	(*GetUserStatsReq)(nil),     // 9: pb.GetUserStatsReq
	(*GetUserStatsResp)(nil),    // 10: pb.GetUserStatsResp
}
var file_pb_search_proto_depIdxs = []int32{
	0,  // 0: pb.SearchFilesResp.list:type_name -> pb.FileItem
	1,  // 1: pb.SearchService.SearchFiles:input_type -> pb.SearchFilesReq
	9,  // 2: pb.SearchService.GetUserStats:input_type -> pb.GetUserStatsReq
	3,  // 3: pb.SearchService.IndexFile:input_type -> pb.IndexFileReq
	5,  // 4: pb.SearchService.UpdateFileIndex:input_type -> pb.UpdateFileIndexReq
	7,  // 5: pb.SearchService.DeleteFileIndex:input_type -> pb.DeleteFileIndexReq
	2,  // 6: pb.SearchService.SearchFiles:output_type -> pb.SearchFilesResp
	10, // 7: pb.SearchService.GetUserStats:output_type -> pb.GetUserStatsResp
	4,  // 8: pb.SearchService.IndexFile:output_type -> pb.IndexFileResp
	6,  // 9: pb.SearchService.UpdateFileIndex:output_type -> pb.UpdateFileIndexResp
	8,  // 10: pb.SearchService.DeleteFileIndex:output_type -> pb.DeleteFileIndexResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pb_search_proto_init() }
func file_pb_search_proto_init() {
	if File_pb_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_search_proto_rawDesc), len(file_pb_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_search_proto_goTypes,
		DependencyIndexes: file_pb_search_proto_depIdxs,
		MessageInfos:      file_pb_search_proto_msgTypes,
	}.Build()
	File_pb_search_proto = out.File
	file_pb_search_proto_goTypes = nil
	file_pb_search_proto_depIdxs = nil
}
