// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: pb/search.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchService_SearchFiles_FullMethodName     = "/pb.SearchService/SearchFiles"
	SearchService_GetUserStats_FullMethodName    = "/pb.SearchService/GetUserStats"
	SearchService_IndexFile_FullMethodName       = "/pb.SearchService/IndexFile"
	SearchService_UpdateFileIndex_FullMethodName = "/pb.SearchService/UpdateFileIndex"
	SearchService_DeleteFileIndex_FullMethodName = "/pb.SearchService/DeleteFileIndex"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	// -------- 搜索接口 --------
	// 搜索文件
	SearchFiles(ctx context.Context, in *SearchFilesReq, opts ...grpc.CallOption) (*SearchFilesResp, error)
	// 获取用户文件统计
	GetUserStats(ctx context.Context, in *GetUserStatsReq, opts ...grpc.CallOption) (*GetUserStatsResp, error)
	// -------- 索引管理（内部调用） --------
	// 索引文件（供 file-rpc 调用，作为 Kafka 的备选方案）
	IndexFile(ctx context.Context, in *IndexFileReq, opts ...grpc.CallOption) (*IndexFileResp, error)
	// 更新文件索引
	UpdateFileIndex(ctx context.Context, in *UpdateFileIndexReq, opts ...grpc.CallOption) (*UpdateFileIndexResp, error)
	// 删除文件索引
	DeleteFileIndex(ctx context.Context, in *DeleteFileIndexReq, opts ...grpc.CallOption) (*DeleteFileIndexResp, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchFiles(ctx context.Context, in *SearchFilesReq, opts ...grpc.CallOption) (*SearchFilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFilesResp)
	err := c.cc.Invoke(ctx, SearchService_SearchFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetUserStats(ctx context.Context, in *GetUserStatsReq, opts ...grpc.CallOption) (*GetUserStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserStatsResp)
	err := c.cc.Invoke(ctx, SearchService_GetUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexFile(ctx context.Context, in *IndexFileReq, opts ...grpc.CallOption) (*IndexFileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexFileResp)
	err := c.cc.Invoke(ctx, SearchService_IndexFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) UpdateFileIndex(ctx context.Context, in *UpdateFileIndexReq, opts ...grpc.CallOption) (*UpdateFileIndexResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFileIndexResp)
	err := c.cc.Invoke(ctx, SearchService_UpdateFileIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) DeleteFileIndex(ctx context.Context, in *DeleteFileIndexReq, opts ...grpc.CallOption) (*DeleteFileIndexResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileIndexResp)
	err := c.cc.Invoke(ctx, SearchService_DeleteFileIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
type SearchServiceServer interface {
	// -------- 搜索接口 --------
	// 搜索文件
	SearchFiles(context.Context, *SearchFilesReq) (*SearchFilesResp, error)
	// 获取用户文件统计
	GetUserStats(context.Context, *GetUserStatsReq) (*GetUserStatsResp, error)
	// -------- 索引管理（内部调用） --------
	// 索引文件（供 file-rpc 调用，作为 Kafka 的备选方案）
	IndexFile(context.Context, *IndexFileReq) (*IndexFileResp, error)
	// 更新文件索引
	UpdateFileIndex(context.Context, *UpdateFileIndexReq) (*UpdateFileIndexResp, error)
	// 删除文件索引
	DeleteFileIndex(context.Context, *DeleteFileIndexReq) (*DeleteFileIndexResp, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) SearchFiles(context.Context, *SearchFilesReq) (*SearchFilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchFiles not implemented")
}
func (UnimplementedSearchServiceServer) GetUserStats(context.Context, *GetUserStatsReq) (*GetUserStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedSearchServiceServer) IndexFile(context.Context, *IndexFileReq) (*IndexFileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexFile not implemented")
}
func (UnimplementedSearchServiceServer) UpdateFileIndex(context.Context, *UpdateFileIndexReq) (*UpdateFileIndexResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFileIndex not implemented")
}
func (UnimplementedSearchServiceServer) DeleteFileIndex(context.Context, *DeleteFileIndexReq) (*DeleteFileIndexResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFileIndex not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchFiles(ctx, req.(*SearchFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetUserStats(ctx, req.(*GetUserStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_IndexFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexFile(ctx, req.(*IndexFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_UpdateFileIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFileIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).UpdateFileIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_UpdateFileIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).UpdateFileIndex(ctx, req.(*UpdateFileIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_DeleteFileIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).DeleteFileIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_DeleteFileIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).DeleteFileIndex(ctx, req.(*DeleteFileIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchFiles",
			Handler:    _SearchService_SearchFiles_Handler,
		},
		{
			MethodName: "GetUserStats",
			Handler:    _SearchService_GetUserStats_Handler,
		},
		{
			MethodName: "IndexFile",
			Handler:    _SearchService_IndexFile_Handler,
		},
		{
			MethodName: "UpdateFileIndex",
			Handler:    _SearchService_UpdateFileIndex_Handler,
		},
		{
			MethodName: "DeleteFileIndex",
			Handler:    _SearchService_DeleteFileIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/search.proto",
}
