// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"polaris-io/backend/pkg/globalkey"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userQuotaFieldNames          = builder.RawFieldNames(&UserQuota{})
	userQuotaRows                = strings.Join(userQuotaFieldNames, ",")
	userQuotaRowsExpectAutoSet   = strings.Join(stringx.Remove(userQuotaFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	userQuotaRowsWithPlaceHolder = strings.Join(stringx.Remove(userQuotaFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	userQuotaModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *UserQuota) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserQuota, error)
		FindOneByUserIdDeleteTime(ctx context.Context, userId uint64, deleteTime uint64) (*UserQuota, error)
		Update(ctx context.Context, session sqlx.Session, data *UserQuota) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserQuota) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *UserQuota) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*UserQuota, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserQuota, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserQuota, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*UserQuota, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*UserQuota, error)
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultUserQuotaModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserQuota struct {
		Id         uint64    `db:"id"`
		UserId     uint64    `db:"user_id"`     // 用户ID
		TotalSize  uint64    `db:"total_size"`  // 总容量(字节)
		UsedSize   uint64    `db:"used_size"`   // 已用容量(字节)
		Version    uint64    `db:"version"`     // 乐观锁版本号
		DelState   int64     `db:"del_state"`   // 删除状态 0:正常 1:已删除
		DeleteTime uint64    `db:"delete_time"` // 删除时间戳
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newUserQuotaModel(conn sqlx.SqlConn) *defaultUserQuotaModel {
	return &defaultUserQuotaModel{
		conn:  conn,
		table: "`user_quota`",
	}
}

func (m *defaultUserQuotaModel) Insert(ctx context.Context, session sqlx.Session, data *UserQuota) (sql.Result, error) {
	data.DeleteTime = 0
	data.DelState = globalkey.DelStateNo

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userQuotaRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.UserId, data.TotalSize, data.UsedSize, data.Version, data.DelState, data.DeleteTime)
	}
	return m.conn.ExecCtx(ctx, query, data.UserId, data.TotalSize, data.UsedSize, data.Version, data.DelState, data.DeleteTime)
}

func (m *defaultUserQuotaModel) FindOne(ctx context.Context, id uint64) (*UserQuota, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  and del_state = ? limit 1", userQuotaRows, m.table)
	var resp UserQuota
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, globalkey.DelStateNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserQuotaModel) FindOneByUserIdDeleteTime(ctx context.Context, userId uint64, deleteTime uint64) (*UserQuota, error) {
	var resp UserQuota
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `delete_time` = ?  and del_state = ? limit 1", userQuotaRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, deleteTime, globalkey.DelStateNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserQuotaModel) Update(ctx context.Context, session sqlx.Session, newData *UserQuota) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userQuotaRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, newData.UserId, newData.TotalSize, newData.UsedSize, newData.Version, newData.DelState, newData.DeleteTime, newData.Id)
	}
	return m.conn.ExecCtx(ctx, query, newData.UserId, newData.TotalSize, newData.UsedSize, newData.Version, newData.DelState, newData.DeleteTime, newData.Id)
}

func (m *defaultUserQuotaModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *UserQuota) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, userQuotaRowsWithPlaceHolder)
	if session != nil {
		sqlResult, err = session.ExecCtx(ctx, query, newData.UserId, newData.TotalSize, newData.UsedSize, newData.Version, newData.DelState, newData.DeleteTime, newData.Id, oldVersion)
	} else {
		sqlResult, err = m.conn.ExecCtx(ctx, query, newData.UserId, newData.TotalSize, newData.UsedSize, newData.Version, newData.DelState, newData.DeleteTime, newData.Id, oldVersion)
	}

	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultUserQuotaModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *UserQuota) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = uint64(time.Now().Unix())
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "UserQuotaModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultUserQuotaModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserQuotaModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserQuotaModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*UserQuota, error) {

	builder = builder.Columns(userQuotaRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserQuota

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserQuotaModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserQuota, error) {

	builder = builder.Columns(userQuotaRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserQuota

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserQuotaModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserQuota, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(userQuotaRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*UserQuota

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultUserQuotaModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*UserQuota, error) {

	builder = builder.Columns(userQuotaRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserQuota

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserQuotaModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*UserQuota, error) {

	builder = builder.Columns(userQuotaRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserQuota

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserQuotaModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultUserQuotaModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultUserQuotaModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserQuotaModel) tableName() string {
	return m.table
}
