// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"shared-board/backend/pkg/globalkey"
)

var (
	roomsFieldNames          = builder.RawFieldNames(&Rooms{})
	roomsRows                = strings.Join(roomsFieldNames, ",")
	roomsRowsExpectAutoSet   = strings.Join(stringx.Remove(roomsFieldNames, "`create_time`", "`update_time`"), ",")
	roomsRowsWithPlaceHolder = strings.Join(stringx.Remove(roomsFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	roomsModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Rooms) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Rooms, error)
		Update(ctx context.Context, session sqlx.Session, data *Rooms) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Rooms) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *Rooms) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*Rooms, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Rooms, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Rooms, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Rooms, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Rooms, error)
		Delete(ctx context.Context, session sqlx.Session, id string) error
	}

	defaultRoomsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Rooms struct {
		Id         string    `db:"id"`          // 房间UUID
		Name       string    `db:"name"`        // 房间名称
		OwnerId    uint64    `db:"owner_id"`    // 房主ID
		Type       int64     `db:"type"`        // 房间类型: 0:公开, 1:加密
		Password   string    `db:"password"`    // 房间密码(仅加密房间有效)
		Status     int64     `db:"status"`      // 状态: 1:活跃, 0:关闭/归档
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
		DeleteTime time.Time `db:"delete_time"` // 删除时间
		DelState   int64     `db:"del_state"`   // 删除状态: 0-正常, 1-已删除
		Version    int64     `db:"version"`     // 版本号(乐观锁)
	}
)

func newRoomsModel(conn sqlx.SqlConn) *defaultRoomsModel {
	return &defaultRoomsModel{
		conn:  conn,
		table: "`rooms`",
	}
}

func (m *defaultRoomsModel) Insert(ctx context.Context, session sqlx.Session, data *Rooms) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.DelState = globalkey.DelStateNo

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, roomsRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Id, data.Name, data.OwnerId, data.Type, data.Password, data.Status, data.DeleteTime, data.DelState, data.Version)
	}
	return m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.OwnerId, data.Type, data.Password, data.Status, data.DeleteTime, data.DelState, data.Version)
}

func (m *defaultRoomsModel) FindOne(ctx context.Context, id string) (*Rooms, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  and del_state = ? limit 1", roomsRows, m.table)
	var resp Rooms
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, globalkey.DelStateNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoomsModel) Update(ctx context.Context, session sqlx.Session, data *Rooms) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, roomsRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Name, data.OwnerId, data.Type, data.Password, data.Status, data.DeleteTime, data.DelState, data.Version, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Name, data.OwnerId, data.Type, data.Password, data.Status, data.DeleteTime, data.DelState, data.Version, data.Id)
}

func (m *defaultRoomsModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Rooms) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, roomsRowsWithPlaceHolder)
	if session != nil {
		sqlResult, err = session.ExecCtx(ctx, query, data.Name, data.OwnerId, data.Type, data.Password, data.Status, data.DeleteTime, data.DelState, data.Version, data.Id, oldVersion)
	} else {
		sqlResult, err = m.conn.ExecCtx(ctx, query, data.Name, data.OwnerId, data.Type, data.Password, data.Status, data.DeleteTime, data.DelState, data.Version, data.Id, oldVersion)
	}

	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultRoomsModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *Rooms) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "RoomsModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultRoomsModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultRoomsModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultRoomsModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*Rooms, error) {

	builder = builder.Columns(roomsRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Rooms

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultRoomsModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Rooms, error) {

	builder = builder.Columns(roomsRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Rooms

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultRoomsModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*Rooms, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(roomsRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*Rooms

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultRoomsModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*Rooms, error) {

	builder = builder.Columns(roomsRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Rooms

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultRoomsModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*Rooms, error) {

	builder = builder.Columns(roomsRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*Rooms

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultRoomsModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultRoomsModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultRoomsModel) Delete(ctx context.Context, session sqlx.Session, id string) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRoomsModel) tableName() string {
	return m.table
}
