// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: file.proto

package server

import (
	"context"

	"polaris-io/backend/app/file/cmd/rpc/internal/logic"
	"polaris-io/backend/app/file/cmd/rpc/internal/svc"
	"polaris-io/backend/app/file/cmd/rpc/pb"
)

type FileServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileServiceServer
}

func NewFileServiceServer(svcCtx *svc.ServiceContext) *FileServiceServer {
	return &FileServiceServer{
		svcCtx: svcCtx,
	}
}

// -------- 上传相关 --------
func (s *FileServiceServer) CheckInstantUpload(ctx context.Context, in *pb.CheckInstantUploadReq) (*pb.CheckInstantUploadResp, error) {
	l := logic.NewCheckInstantUploadLogic(ctx, s.svcCtx)
	return l.CheckInstantUpload(in)
}

// 获取预签名上传 URL
func (s *FileServiceServer) GetPresignedUploadUrl(ctx context.Context, in *pb.GetPresignedUploadUrlReq) (*pb.GetPresignedUploadUrlResp, error) {
	l := logic.NewGetPresignedUploadUrlLogic(ctx, s.svcCtx)
	return l.GetPresignedUploadUrl(in)
}

// 创建文件记录 (上传完成后调用)
func (s *FileServiceServer) CreateFile(ctx context.Context, in *pb.CreateFileReq) (*pb.CreateFileResp, error) {
	l := logic.NewCreateFileLogic(ctx, s.svcCtx)
	return l.CreateFile(in)
}

// -------- 文件夹管理 --------
func (s *FileServiceServer) CreateFolder(ctx context.Context, in *pb.CreateFolderReq) (*pb.CreateFolderResp, error) {
	l := logic.NewCreateFolderLogic(ctx, s.svcCtx)
	return l.CreateFolder(in)
}

// -------- 文件查询 (供其他服务调用) --------
func (s *FileServiceServer) GetFileInfo(ctx context.Context, in *pb.GetFileInfoReq) (*pb.GetFileInfoResp, error) {
	l := logic.NewGetFileInfoLogic(ctx, s.svcCtx)
	return l.GetFileInfo(in)
}

// 批量获取文件信息
func (s *FileServiceServer) GetFilesByIds(ctx context.Context, in *pb.GetFilesByIdsReq) (*pb.GetFilesByIdsResp, error) {
	l := logic.NewGetFilesByIdsLogic(ctx, s.svcCtx)
	return l.GetFilesByIds(in)
}

// 检查文件是否存在
func (s *FileServiceServer) CheckFileExists(ctx context.Context, in *pb.CheckFileExistsReq) (*pb.CheckFileExistsResp, error) {
	l := logic.NewCheckFileExistsLogic(ctx, s.svcCtx)
	return l.CheckFileExists(in)
}

// 列出目录内容
func (s *FileServiceServer) ListFiles(ctx context.Context, in *pb.ListFilesReq) (*pb.ListFilesResp, error) {
	l := logic.NewListFilesLogic(ctx, s.svcCtx)
	return l.ListFiles(in)
}

// 获取文件路径 (面包屑)
func (s *FileServiceServer) GetFilePath(ctx context.Context, in *pb.GetFilePathReq) (*pb.GetFilePathResp, error) {
	l := logic.NewGetFilePathLogic(ctx, s.svcCtx)
	return l.GetFilePath(in)
}

// -------- 文件操作 --------
func (s *FileServiceServer) GetDownloadUrl(ctx context.Context, in *pb.GetDownloadUrlReq) (*pb.GetDownloadUrlResp, error) {
	l := logic.NewGetDownloadUrlLogic(ctx, s.svcCtx)
	return l.GetDownloadUrl(in)
}

// 移动文件/文件夹
func (s *FileServiceServer) MoveFiles(ctx context.Context, in *pb.MoveFilesReq) (*pb.MoveFilesResp, error) {
	l := logic.NewMoveFilesLogic(ctx, s.svcCtx)
	return l.MoveFiles(in)
}

// 重命名
func (s *FileServiceServer) RenameFile(ctx context.Context, in *pb.RenameFileReq) (*pb.RenameFileResp, error) {
	l := logic.NewRenameFileLogic(ctx, s.svcCtx)
	return l.RenameFile(in)
}

// 复制文件/文件夹
func (s *FileServiceServer) CopyFiles(ctx context.Context, in *pb.CopyFilesReq) (*pb.CopyFilesResp, error) {
	l := logic.NewCopyFilesLogic(ctx, s.svcCtx)
	return l.CopyFiles(in)
}

// 软删除 (移入回收站)
func (s *FileServiceServer) SoftDeleteFiles(ctx context.Context, in *pb.SoftDeleteFilesReq) (*pb.SoftDeleteFilesResp, error) {
	l := logic.NewSoftDeleteFilesLogic(ctx, s.svcCtx)
	return l.SoftDeleteFiles(in)
}

// -------- 回收站 --------
func (s *FileServiceServer) ListTrash(ctx context.Context, in *pb.ListTrashReq) (*pb.ListTrashResp, error) {
	l := logic.NewListTrashLogic(ctx, s.svcCtx)
	return l.ListTrash(in)
}

// 恢复文件
func (s *FileServiceServer) RestoreFiles(ctx context.Context, in *pb.RestoreFilesReq) (*pb.RestoreFilesResp, error) {
	l := logic.NewRestoreFilesLogic(ctx, s.svcCtx)
	return l.RestoreFiles(in)
}

// 彻底删除
func (s *FileServiceServer) HardDeleteFiles(ctx context.Context, in *pb.HardDeleteFilesReq) (*pb.HardDeleteFilesResp, error) {
	l := logic.NewHardDeleteFilesLogic(ctx, s.svcCtx)
	return l.HardDeleteFiles(in)
}

// 清空回收站
func (s *FileServiceServer) ClearTrash(ctx context.Context, in *pb.ClearTrashReq) (*pb.ClearTrashResp, error) {
	l := logic.NewClearTrashLogic(ctx, s.svcCtx)
	return l.ClearTrash(in)
}

// -------- 内部方法 --------
func (s *FileServiceServer) CalcUserUsedSize(ctx context.Context, in *pb.CalcUserUsedSizeReq) (*pb.CalcUserUsedSizeResp, error) {
	l := logic.NewCalcUserUsedSizeLogic(ctx, s.svcCtx)
	return l.CalcUserUsedSize(in)
}
