// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: file.proto

package fileservice

import (
	"context"

	"polaris-io/backend/app/file/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CalcUserUsedSizeReq       = pb.CalcUserUsedSizeReq
	CalcUserUsedSizeResp      = pb.CalcUserUsedSizeResp
	CheckFileExistsReq        = pb.CheckFileExistsReq
	CheckFileExistsResp       = pb.CheckFileExistsResp
	CheckInstantUploadReq     = pb.CheckInstantUploadReq
	CheckInstantUploadResp    = pb.CheckInstantUploadResp
	ClearTrashReq             = pb.ClearTrashReq
	ClearTrashResp            = pb.ClearTrashResp
	CopyFilesReq              = pb.CopyFilesReq
	CopyFilesResp             = pb.CopyFilesResp
	CreateFileReq             = pb.CreateFileReq
	CreateFileResp            = pb.CreateFileResp
	CreateFolderReq           = pb.CreateFolderReq
	CreateFolderResp          = pb.CreateFolderResp
	FileInfo                  = pb.FileInfo
	FileMeta                  = pb.FileMeta
	GetDownloadUrlReq         = pb.GetDownloadUrlReq
	GetDownloadUrlResp        = pb.GetDownloadUrlResp
	GetFileInfoReq            = pb.GetFileInfoReq
	GetFileInfoResp           = pb.GetFileInfoResp
	GetFilePathReq            = pb.GetFilePathReq
	GetFilePathResp           = pb.GetFilePathResp
	GetFilesByIdsReq          = pb.GetFilesByIdsReq
	GetFilesByIdsResp         = pb.GetFilesByIdsResp
	GetPresignedUploadUrlReq  = pb.GetPresignedUploadUrlReq
	GetPresignedUploadUrlResp = pb.GetPresignedUploadUrlResp
	HardDeleteFilesReq        = pb.HardDeleteFilesReq
	HardDeleteFilesResp       = pb.HardDeleteFilesResp
	ListFilesReq              = pb.ListFilesReq
	ListFilesResp             = pb.ListFilesResp
	ListTrashReq              = pb.ListTrashReq
	ListTrashResp             = pb.ListTrashResp
	MoveFilesReq              = pb.MoveFilesReq
	MoveFilesResp             = pb.MoveFilesResp
	RenameFileReq             = pb.RenameFileReq
	RenameFileResp            = pb.RenameFileResp
	RestoreFilesReq           = pb.RestoreFilesReq
	RestoreFilesResp          = pb.RestoreFilesResp
	SoftDeleteFilesReq        = pb.SoftDeleteFilesReq
	SoftDeleteFilesResp       = pb.SoftDeleteFilesResp

	FileService interface {
		// -------- 上传相关 --------
		CheckInstantUpload(ctx context.Context, in *CheckInstantUploadReq, opts ...grpc.CallOption) (*CheckInstantUploadResp, error)
		// 获取预签名上传 URL
		GetPresignedUploadUrl(ctx context.Context, in *GetPresignedUploadUrlReq, opts ...grpc.CallOption) (*GetPresignedUploadUrlResp, error)
		// 创建文件记录 (上传完成后调用)
		CreateFile(ctx context.Context, in *CreateFileReq, opts ...grpc.CallOption) (*CreateFileResp, error)
		// -------- 文件夹管理 --------
		CreateFolder(ctx context.Context, in *CreateFolderReq, opts ...grpc.CallOption) (*CreateFolderResp, error)
		// -------- 文件查询 (供其他服务调用) --------
		GetFileInfo(ctx context.Context, in *GetFileInfoReq, opts ...grpc.CallOption) (*GetFileInfoResp, error)
		// 批量获取文件信息
		GetFilesByIds(ctx context.Context, in *GetFilesByIdsReq, opts ...grpc.CallOption) (*GetFilesByIdsResp, error)
		// 检查文件是否存在
		CheckFileExists(ctx context.Context, in *CheckFileExistsReq, opts ...grpc.CallOption) (*CheckFileExistsResp, error)
		// 列出目录内容
		ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesResp, error)
		// 获取文件路径 (面包屑)
		GetFilePath(ctx context.Context, in *GetFilePathReq, opts ...grpc.CallOption) (*GetFilePathResp, error)
		// -------- 文件操作 --------
		GetDownloadUrl(ctx context.Context, in *GetDownloadUrlReq, opts ...grpc.CallOption) (*GetDownloadUrlResp, error)
		// 移动文件/文件夹
		MoveFiles(ctx context.Context, in *MoveFilesReq, opts ...grpc.CallOption) (*MoveFilesResp, error)
		// 重命名
		RenameFile(ctx context.Context, in *RenameFileReq, opts ...grpc.CallOption) (*RenameFileResp, error)
		// 复制文件/文件夹
		CopyFiles(ctx context.Context, in *CopyFilesReq, opts ...grpc.CallOption) (*CopyFilesResp, error)
		// 软删除 (移入回收站)
		SoftDeleteFiles(ctx context.Context, in *SoftDeleteFilesReq, opts ...grpc.CallOption) (*SoftDeleteFilesResp, error)
		// -------- 回收站 --------
		ListTrash(ctx context.Context, in *ListTrashReq, opts ...grpc.CallOption) (*ListTrashResp, error)
		// 恢复文件
		RestoreFiles(ctx context.Context, in *RestoreFilesReq, opts ...grpc.CallOption) (*RestoreFilesResp, error)
		// 彻底删除
		HardDeleteFiles(ctx context.Context, in *HardDeleteFilesReq, opts ...grpc.CallOption) (*HardDeleteFilesResp, error)
		// 清空回收站
		ClearTrash(ctx context.Context, in *ClearTrashReq, opts ...grpc.CallOption) (*ClearTrashResp, error)
		// -------- 内部方法 --------
		CalcUserUsedSize(ctx context.Context, in *CalcUserUsedSizeReq, opts ...grpc.CallOption) (*CalcUserUsedSizeResp, error)
	}

	defaultFileService struct {
		cli zrpc.Client
	}
)

func NewFileService(cli zrpc.Client) FileService {
	return &defaultFileService{
		cli: cli,
	}
}

// -------- 上传相关 --------
func (m *defaultFileService) CheckInstantUpload(ctx context.Context, in *CheckInstantUploadReq, opts ...grpc.CallOption) (*CheckInstantUploadResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.CheckInstantUpload(ctx, in, opts...)
}

// 获取预签名上传 URL
func (m *defaultFileService) GetPresignedUploadUrl(ctx context.Context, in *GetPresignedUploadUrlReq, opts ...grpc.CallOption) (*GetPresignedUploadUrlResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.GetPresignedUploadUrl(ctx, in, opts...)
}

// 创建文件记录 (上传完成后调用)
func (m *defaultFileService) CreateFile(ctx context.Context, in *CreateFileReq, opts ...grpc.CallOption) (*CreateFileResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.CreateFile(ctx, in, opts...)
}

// -------- 文件夹管理 --------
func (m *defaultFileService) CreateFolder(ctx context.Context, in *CreateFolderReq, opts ...grpc.CallOption) (*CreateFolderResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.CreateFolder(ctx, in, opts...)
}

// -------- 文件查询 (供其他服务调用) --------
func (m *defaultFileService) GetFileInfo(ctx context.Context, in *GetFileInfoReq, opts ...grpc.CallOption) (*GetFileInfoResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.GetFileInfo(ctx, in, opts...)
}

// 批量获取文件信息
func (m *defaultFileService) GetFilesByIds(ctx context.Context, in *GetFilesByIdsReq, opts ...grpc.CallOption) (*GetFilesByIdsResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.GetFilesByIds(ctx, in, opts...)
}

// 检查文件是否存在
func (m *defaultFileService) CheckFileExists(ctx context.Context, in *CheckFileExistsReq, opts ...grpc.CallOption) (*CheckFileExistsResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.CheckFileExists(ctx, in, opts...)
}

// 列出目录内容
func (m *defaultFileService) ListFiles(ctx context.Context, in *ListFilesReq, opts ...grpc.CallOption) (*ListFilesResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.ListFiles(ctx, in, opts...)
}

// 获取文件路径 (面包屑)
func (m *defaultFileService) GetFilePath(ctx context.Context, in *GetFilePathReq, opts ...grpc.CallOption) (*GetFilePathResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.GetFilePath(ctx, in, opts...)
}

// -------- 文件操作 --------
func (m *defaultFileService) GetDownloadUrl(ctx context.Context, in *GetDownloadUrlReq, opts ...grpc.CallOption) (*GetDownloadUrlResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.GetDownloadUrl(ctx, in, opts...)
}

// 移动文件/文件夹
func (m *defaultFileService) MoveFiles(ctx context.Context, in *MoveFilesReq, opts ...grpc.CallOption) (*MoveFilesResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.MoveFiles(ctx, in, opts...)
}

// 重命名
func (m *defaultFileService) RenameFile(ctx context.Context, in *RenameFileReq, opts ...grpc.CallOption) (*RenameFileResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.RenameFile(ctx, in, opts...)
}

// 复制文件/文件夹
func (m *defaultFileService) CopyFiles(ctx context.Context, in *CopyFilesReq, opts ...grpc.CallOption) (*CopyFilesResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.CopyFiles(ctx, in, opts...)
}

// 软删除 (移入回收站)
func (m *defaultFileService) SoftDeleteFiles(ctx context.Context, in *SoftDeleteFilesReq, opts ...grpc.CallOption) (*SoftDeleteFilesResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.SoftDeleteFiles(ctx, in, opts...)
}

// -------- 回收站 --------
func (m *defaultFileService) ListTrash(ctx context.Context, in *ListTrashReq, opts ...grpc.CallOption) (*ListTrashResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.ListTrash(ctx, in, opts...)
}

// 恢复文件
func (m *defaultFileService) RestoreFiles(ctx context.Context, in *RestoreFilesReq, opts ...grpc.CallOption) (*RestoreFilesResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.RestoreFiles(ctx, in, opts...)
}

// 彻底删除
func (m *defaultFileService) HardDeleteFiles(ctx context.Context, in *HardDeleteFilesReq, opts ...grpc.CallOption) (*HardDeleteFilesResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.HardDeleteFiles(ctx, in, opts...)
}

// 清空回收站
func (m *defaultFileService) ClearTrash(ctx context.Context, in *ClearTrashReq, opts ...grpc.CallOption) (*ClearTrashResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.ClearTrash(ctx, in, opts...)
}

// -------- 内部方法 --------
func (m *defaultFileService) CalcUserUsedSize(ctx context.Context, in *CalcUserUsedSizeReq, opts ...grpc.CallOption) (*CalcUserUsedSizeResp, error) {
	client := pb.NewFileServiceClient(m.cli.Conn())
	return client.CalcUserUsedSize(ctx, in, opts...)
}
