// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Mobile   string `json:"mobile" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile" validate:"required,len=11"`  // 手机号
	Password string `json:"password" validate:"required,min=6"` // 密码
	Name     string `json:"name,optional"`                      // 昵称 (可选)
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type User struct {
	Id     int64  `json:"id"`
	Mobile string `json:"mobile"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Info   string `json:"info"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	User User `json:"user"`
}

type UserQuota struct {
	TotalSize uint64 `json:"totalSize"` // 总容量 (字节)
	UsedSize  uint64 `json:"usedSize"`  // 已用容量 (字节)
}

type UserQuotaReq struct {
}

type UserQuotaResp struct {
	Quota UserQuota `json:"quota"`
}
