// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	search "polaris-io/backend/app/search/cmd/api/internal/handler/search"
	"polaris-io/backend/app/search/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 搜索文件
				Method:  http.MethodGet,
				Path:    "/files",
				Handler: search.SearchFilesHandler(serverCtx),
			},
			{
				// 获取用户文件统计
				Method:  http.MethodGet,
				Path:    "/stats",
				Handler: search.GetUserStatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/search/v1"),
	)
}
