// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	file "polaris-io/backend/app/file/cmd/api/internal/handler/file"
	folder "polaris-io/backend/app/file/cmd/api/internal/handler/folder"
	trash "polaris-io/backend/app/file/cmd/api/internal/handler/trash"
	upload "polaris-io/backend/app/file/cmd/api/internal/handler/upload"
	"polaris-io/backend/app/file/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 复制文件/文件夹
				Method:  http.MethodPost,
				Path:    "/copy",
				Handler: file.FileCopyHandler(serverCtx),
			},
			{
				// 删除文件/文件夹 (移入回收站)
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: file.FileDeleteHandler(serverCtx),
			},
			{
				// 获取文件详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: file.FileDetailHandler(serverCtx),
			},
			{
				// 获取下载URL
				Method:  http.MethodGet,
				Path:    "/download",
				Handler: file.FileDownloadHandler(serverCtx),
			},
			{
				// 列出目录内容
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: file.FileListHandler(serverCtx),
			},
			{
				// 移动文件/文件夹
				Method:  http.MethodPost,
				Path:    "/move",
				Handler: file.FileMoveHandler(serverCtx),
			},
			{
				// 重命名文件/文件夹
				Method:  http.MethodPost,
				Path:    "/rename",
				Handler: file.FileRenameHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/file/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建文件夹
				Method:  http.MethodPost,
				Path:    "/folder/create",
				Handler: folder.FolderCreateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/file/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 清空回收站
				Method:  http.MethodPost,
				Path:    "/trash/clear",
				Handler: trash.TrashClearHandler(serverCtx),
			},
			{
				// 彻底删除
				Method:  http.MethodPost,
				Path:    "/trash/delete",
				Handler: trash.TrashDeleteHandler(serverCtx),
			},
			{
				// 回收站列表
				Method:  http.MethodGet,
				Path:    "/trash/list",
				Handler: trash.TrashListHandler(serverCtx),
			},
			{
				// 恢复文件
				Method:  http.MethodPost,
				Path:    "/trash/restore",
				Handler: trash.TrashRestoreHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/file/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 秒传检查 - 检查文件是否已存在
				Method:  http.MethodPost,
				Path:    "/upload/check",
				Handler: upload.UploadCheckHandler(serverCtx),
			},
			{
				// 上传完成回调
				Method:  http.MethodPost,
				Path:    "/upload/complete",
				Handler: upload.UploadCompleteHandler(serverCtx),
			},
			{
				// 获取预签名上传URL
				Method:  http.MethodPost,
				Path:    "/upload/presign",
				Handler: upload.UploadPresignHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/file/v1"),
	)
}
