// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	access "polaris-io/backend/app/share/cmd/api/internal/handler/access"
	save "polaris-io/backend/app/share/cmd/api/internal/handler/save"
	share "polaris-io/backend/app/share/cmd/api/internal/handler/share"
	"polaris-io/backend/app/share/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取分享详情（验证提取码）
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: access.ShareDetailHandler(serverCtx),
			},
			{
				// 获取分享文件下载链接
				Method:  http.MethodGet,
				Path:    "/download",
				Handler: access.ShareDownloadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/share/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 保存分享到我的网盘
				Method:  http.MethodPost,
				Path:    "/save",
				Handler: save.SaveShareHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/share/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 取消分享
				Method:  http.MethodPost,
				Path:    "/cancel",
				Handler: share.CancelShareHandler(serverCtx),
			},
			{
				// 创建分享
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: share.CreateShareHandler(serverCtx),
			},
			{
				// 我的分享列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: share.ShareListHandler(serverCtx),
			},
			{
				// 更新分享
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: share.UpdateShareHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/share/v1"),
	)
}
