// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"polaris-io/backend/pkg/globalkey"
)

var (
	userRepositoryFieldNames          = builder.RawFieldNames(&UserRepository{})
	userRepositoryRows                = strings.Join(userRepositoryFieldNames, ",")
	userRepositoryRowsExpectAutoSet   = strings.Join(stringx.Remove(userRepositoryFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	userRepositoryRowsWithPlaceHolder = strings.Join(stringx.Remove(userRepositoryFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheUserRepositoryIdPrefix       = "cache:userRepository:id:"
	cacheUserRepositoryIdentityPrefix = "cache:userRepository:identity:"
)

type (
	userRepositoryModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *UserRepository) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserRepository, error)
		FindOneByIdentity(ctx context.Context, identity string) (*UserRepository, error)
		Update(ctx context.Context, session sqlx.Session, data *UserRepository) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *UserRepository) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *UserRepository) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*UserRepository, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRepository, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRepository, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*UserRepository, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*UserRepository, error)
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultUserRepositoryModel struct {
		sqlc.CachedConn
		table string
	}

	UserRepository struct {
		Id         uint64    `db:"id"`
		Identity   string    `db:"identity"`    // 文件唯一标识
		Hash       string    `db:"hash"`        // 文件指纹
		UserId     uint64    `db:"user_id"`     // 用户ID
		ParentId   uint64    `db:"parent_id"`   // 父目录ID
		Name       string    `db:"name"`        // 文件名
		Ext        string    `db:"ext"`         // 扩展名
		Size       uint64    `db:"size"`        // 文件大小
		Path       string    `db:"path"`        // 物理路径
		Version    uint64    `db:"version"`     // 乐观锁版本号
		DelState   int64     `db:"del_state"`   // 删除状态 0:正常 1:已删除
		DeleteTime uint64    `db:"delete_time"` // 删除时间戳(0:未删 >0:已删)
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newUserRepositoryModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserRepositoryModel {
	return &defaultUserRepositoryModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_repository`",
	}
}

func (m *defaultUserRepositoryModel) Insert(ctx context.Context, session sqlx.Session, data *UserRepository) (sql.Result, error) {
	data.DeleteTime = 0
	data.DelState = globalkey.DelStateNo
	userRepositoryIdKey := fmt.Sprintf("%s%v", cacheUserRepositoryIdPrefix, data.Id)
	userRepositoryIdentityKey := fmt.Sprintf("%s%v", cacheUserRepositoryIdentityPrefix, data.Identity)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRepositoryRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Identity, data.Hash, data.UserId, data.ParentId, data.Name, data.Ext, data.Size, data.Path, data.Version, data.DelState, data.DeleteTime)
		}
		return conn.ExecCtx(ctx, query, data.Identity, data.Hash, data.UserId, data.ParentId, data.Name, data.Ext, data.Size, data.Path, data.Version, data.DelState, data.DeleteTime)
	}, userRepositoryIdKey, userRepositoryIdentityKey)
}

func (m *defaultUserRepositoryModel) FindOne(ctx context.Context, id uint64) (*UserRepository, error) {
	userRepositoryIdKey := fmt.Sprintf("%s%v", cacheUserRepositoryIdPrefix, id)
	var resp UserRepository
	err := m.QueryRowCtx(ctx, &resp, userRepositoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", userRepositoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRepositoryModel) FindOneByIdentity(ctx context.Context, identity string) (*UserRepository, error) {
	userRepositoryIdentityKey := fmt.Sprintf("%s%v", cacheUserRepositoryIdentityPrefix, identity)
	var resp UserRepository
	err := m.QueryRowIndexCtx(ctx, &resp, userRepositoryIdentityKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `identity` = ? and del_state = ? limit 1", userRepositoryRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, identity, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRepositoryModel) Update(ctx context.Context, session sqlx.Session, newData *UserRepository) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	userRepositoryIdKey := fmt.Sprintf("%s%v", cacheUserRepositoryIdPrefix, data.Id)
	userRepositoryIdentityKey := fmt.Sprintf("%s%v", cacheUserRepositoryIdentityPrefix, data.Identity)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRepositoryRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.Identity, newData.Hash, newData.UserId, newData.ParentId, newData.Name, newData.Ext, newData.Size, newData.Path, newData.Version, newData.DelState, newData.DeleteTime, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.Identity, newData.Hash, newData.UserId, newData.ParentId, newData.Name, newData.Ext, newData.Size, newData.Path, newData.Version, newData.DelState, newData.DeleteTime, newData.Id)
	}, userRepositoryIdKey, userRepositoryIdentityKey)
}

func (m *defaultUserRepositoryModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *UserRepository) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	userRepositoryIdKey := fmt.Sprintf("%s%v", cacheUserRepositoryIdPrefix, data.Id)
	userRepositoryIdentityKey := fmt.Sprintf("%s%v", cacheUserRepositoryIdentityPrefix, data.Identity)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, userRepositoryRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.Identity, newData.Hash, newData.UserId, newData.ParentId, newData.Name, newData.Ext, newData.Size, newData.Path, newData.Version, newData.DelState, newData.DeleteTime, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.Identity, newData.Hash, newData.UserId, newData.ParentId, newData.Name, newData.Ext, newData.Size, newData.Path, newData.Version, newData.DelState, newData.DeleteTime, newData.Id, oldVersion)
	}, userRepositoryIdKey, userRepositoryIdentityKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultUserRepositoryModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *UserRepository) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = uint64(time.Now().Unix())
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "UserRepositoryModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultUserRepositoryModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserRepositoryModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserRepositoryModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*UserRepository, error) {

	builder = builder.Columns(userRepositoryRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRepository
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRepositoryModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRepository, error) {

	builder = builder.Columns(userRepositoryRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRepository
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRepositoryModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*UserRepository, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(userRepositoryRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*UserRepository
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultUserRepositoryModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*UserRepository, error) {

	builder = builder.Columns(userRepositoryRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRepository
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRepositoryModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*UserRepository, error) {

	builder = builder.Columns(userRepositoryRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*UserRepository
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserRepositoryModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultUserRepositoryModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultUserRepositoryModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userRepositoryIdKey := fmt.Sprintf("%s%v", cacheUserRepositoryIdPrefix, id)
	userRepositoryIdentityKey := fmt.Sprintf("%s%v", cacheUserRepositoryIdentityPrefix, data.Identity)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, userRepositoryIdKey, userRepositoryIdentityKey)
	return err
}
func (m *defaultUserRepositoryModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserRepositoryIdPrefix, primary)
}
func (m *defaultUserRepositoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", userRepositoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultUserRepositoryModel) tableName() string {
	return m.table
}
