// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CancelShareReq struct {
	Identities []string `json:"identities"` // 分享标识列表
}

type CancelShareResp struct {
	CancelledCount int64 `json:"cancelledCount"`
}

type CreateShareReq struct {
	RepositoryIdentity string `json:"repositoryIdentity"` // 文件Identity
	ExpiredType        int64  `json:"expiredType"`        // 有效期类型: 0永久 1:1天 7:7天 30:30天
	HasCode            bool   `json:"hasCode"`            // 是否需要提取码
}

type CreateShareResp struct {
	Identity string `json:"identity"` // 分享标识
	Code     string `json:"code"`     // 提取码（如果设置了）
	Url      string `json:"url"`      // 分享链接
}

type SaveShareReq struct {
	Identity       string   `json:"identity"`       // 分享标识
	Code           string   `json:"code"`           // 提取码
	FileIdentities []string `json:"fileIdentities"` // 要保存的文件Identity列表（文件夹分享时选择部分保存）
	TargetFolderId int64    `json:"targetFolderId"` // 目标文件夹ID（0=根目录）
}

type SaveShareResp struct {
	SavedCount int64 `json:"savedCount"` // 保存成功的文件数量
}

type ShareDetailReq struct {
	Identity string `form:"identity"` // 分享标识
	Code     string `form:"code"`     // 提取码
}

type ShareDetailResp struct {
	File        ShareFileInfo   `json:"file"`        // 分享的文件信息
	SharerName  string          `json:"sharerName"`  // 分享者名称
	ExpiredTime int64           `json:"expiredTime"` // 失效时间
	Children    []ShareFileInfo `json:"children"`    // 如果是文件夹，包含子文件列表
}

type ShareDownloadReq struct {
	Identity     string `form:"identity"`     // 分享标识
	Code         string `form:"code"`         // 提取码
	FileIdentity string `form:"fileIdentity"` // 要下载的文件Identity（文件夹分享时需要）
}

type ShareDownloadResp struct {
	Url string `json:"url"` // 下载链接
}

type ShareFileInfo struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
	Ext      string `json:"ext"`
	Size     uint64 `json:"size"`
	IsDir    bool   `json:"isDir"`
}

type ShareItem struct {
	Id                 int64  `json:"id"`
	Identity           string `json:"identity"`           // 分享唯一标识
	UserId             int64  `json:"userId"`             // 分享者ID
	RepositoryIdentity string `json:"repositoryIdentity"` // 关联文件Identity
	FileName           string `json:"fileName"`           // 文件名（从file服务获取）
	FileExt            string `json:"fileExt"`            // 文件扩展名
	FileSize           uint64 `json:"fileSize"`           // 文件大小
	IsDir              bool   `json:"isDir"`              // 是否为文件夹
	Code               string `json:"code"`               // 提取码（创建者可见）
	ClickNum           int64  `json:"clickNum"`           // 点击次数
	ExpiredTime        int64  `json:"expiredTime"`        // 失效时间戳（0=永久）
	Status             int64  `json:"status"`             // 状态 0:正常 1:已封禁
	CreateTime         int64  `json:"createTime"`         // 创建时间
}

type ShareListReq struct {
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type ShareListResp struct {
	List  []ShareItem `json:"list"`
	Total int64       `json:"total"`
}

type UpdateShareReq struct {
	Identity    string `json:"identity"`             // 分享标识
	ExpiredType int64  `json:"expiredType,optional"` // 新的有效期类型
	Code        string `json:"code,optional"`        // 新的提取码（空字符串=取消提取码）
}

type UpdateShareResp struct {
}
