// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type FileCopyReq struct {
	Identities []string `json:"identities" validate:"required,min=1"` // 文件标识列表
	TargetId   int64    `json:"targetId"`                             // 目标目录ID (0=根目录)
}

type FileCopyResp struct {
}

type FileDeleteReq struct {
	Identities []string `json:"identities" validate:"required,min=1"` // 文件标识列表
}

type FileDeleteResp struct {
}

type FileDetailReq struct {
	Identity string `form:"identity" validate:"required"` // 文件标识
}

type FileDetailResp struct {
	File FileItem   `json:"file"`
	Path []FileItem `json:"path"` // 路径面包屑 (从根目录到当前文件)
}

type FileDownloadReq struct {
	Identity string `form:"identity" validate:"required"` // 文件标识
}

type FileDownloadResp struct {
	Url string `json:"url"` // 预签名下载 URL
}

type FileItem struct {
	Id         int64  `json:"id"`
	Identity   string `json:"identity"`   // 文件唯一标识 (UUID)
	Name       string `json:"name"`       // 文件名
	Ext        string `json:"ext"`        // 扩展名 (文件夹为空)
	Size       uint64 `json:"size"`       // 文件大小 (字节)
	IsDir      bool   `json:"isDir"`      // 是否为文件夹
	ParentId   int64  `json:"parentId"`   // 父目录ID
	CreateTime int64  `json:"createTime"` // 创建时间戳
	UpdateTime int64  `json:"updateTime"` // 更新时间戳
}

type FileListReq struct {
	ParentId int64  `form:"parentId,default=0"`  // 父目录ID (0=根目录)
	Page     int64  `form:"page,default=1"`      // 页码
	PageSize int64  `form:"pageSize,default=20"` // 每页数量
	OrderBy  string `form:"orderBy,optional"`    // 排序字段: name, size, create_time
	Order    string `form:"order,optional"`      // 排序方向: asc, desc
}

type FileListResp struct {
	List  []FileItem `json:"list"`
	Total int64      `json:"total"`
}

type FileMoveReq struct {
	Identities []string `json:"identities" validate:"required,min=1"` // 文件标识列表
	TargetId   int64    `json:"targetId"`                             // 目标目录ID (0=根目录)
}

type FileMoveResp struct {
}

type FileRenameReq struct {
	Identity string `json:"identity" validate:"required"`     // 文件标识
	Name     string `json:"name" validate:"required,max=255"` // 新名称
}

type FileRenameResp struct {
}

type FolderCreateReq struct {
	Name     string `json:"name" validate:"required,max=255"` // 文件夹名
	ParentId int64  `json:"parentId,default=0"`               // 父目录ID (0=根目录)
}

type FolderCreateResp struct {
	Identity string `json:"identity"` // 文件夹唯一标识
}

type TrashClearReq struct {
}

type TrashClearResp struct {
}

type TrashDeleteReq struct {
	Identities []string `json:"identities" validate:"required,min=1"` // 文件标识列表
}

type TrashDeleteResp struct {
}

type TrashItem struct {
	Id         int64  `json:"id"`
	Identity   string `json:"identity"`
	Name       string `json:"name"`
	Ext        string `json:"ext"`
	Size       uint64 `json:"size"`
	IsDir      bool   `json:"isDir"`
	DeleteTime int64  `json:"deleteTime"` // 删除时间戳
}

type TrashListReq struct {
	Page     int64 `form:"page,default=1"`      // 页码
	PageSize int64 `form:"pageSize,default=20"` // 每页数量
}

type TrashListResp struct {
	List  []TrashItem `json:"list"`
	Total int64       `json:"total"`
}

type TrashRestoreReq struct {
	Identities []string `json:"identities" validate:"required,min=1"` // 文件标识列表
}

type TrashRestoreResp struct {
}

type UploadCheckReq struct {
	Hash string `json:"hash" validate:"required"` // 文件 SHA256
	Size uint64 `json:"size" validate:"required"` // 文件大小 (字节)
	Name string `json:"name" validate:"required"` // 文件名
	Ext  string `json:"ext"`                      // 扩展名
}

type UploadCheckResp struct {
	Exists   bool   `json:"exists"`             // 是否已存在 (秒传成功)
	Identity string `json:"identity,omitempty"` // 秒传成功时返回文件标识
}

type UploadCompleteReq struct {
	UploadKey string `json:"uploadKey" validate:"required"` // 上传凭证
	Hash      string `json:"hash" validate:"required"`      // 文件 SHA256
	Size      uint64 `json:"size" validate:"required"`      // 文件大小
	Name      string `json:"name" validate:"required"`      // 文件名
	Ext       string `json:"ext"`                           // 扩展名
	MimeType  string `json:"mimeType"`                      // MIME 类型
	ParentId  int64  `json:"parentId,default=0"`            // 父目录ID
}

type UploadCompleteResp struct {
	Identity string `json:"identity"` // 文件唯一标识
}

type UploadPresignReq struct {
	Hash     string `json:"hash" validate:"required"` // 文件 SHA256
	Size     uint64 `json:"size" validate:"required"` // 文件大小
	Name     string `json:"name" validate:"required"` // 文件名
	Ext      string `json:"ext"`                      // 扩展名
	MimeType string `json:"mimeType"`                 // MIME 类型
	ParentId int64  `json:"parentId,default=0"`       // 父目录ID (0=根目录)
}

type UploadPresignResp struct {
	UploadUrl string `json:"uploadUrl"` // S3 预签名上传 URL
	UploadKey string `json:"uploadKey"` // 上传凭证 (用于 complete 接口)
}
