// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"shared-board/backend/pkg/globalkey"
)

var (
	chatMessagesFieldNames          = builder.RawFieldNames(&ChatMessages{})
	chatMessagesRows                = strings.Join(chatMessagesFieldNames, ",")
	chatMessagesRowsExpectAutoSet   = strings.Join(stringx.Remove(chatMessagesFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	chatMessagesRowsWithPlaceHolder = strings.Join(stringx.Remove(chatMessagesFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	chatMessagesModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ChatMessages) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ChatMessages, error)
		Update(ctx context.Context, session sqlx.Session, data *ChatMessages) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ChatMessages) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *ChatMessages) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ChatMessages, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatMessages, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatMessages, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ChatMessages, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ChatMessages, error)
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultChatMessagesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChatMessages struct {
		Id         uint64         `db:"id"`          // 主键ID
		RoomId     string         `db:"room_id"`     // 房间ID
		UserId     uint64         `db:"user_id"`     // 发送者ID
		Content    sql.NullString `db:"content"`     // 消息内容
		MsgType    int64          `db:"msg_type"`    // 消息类型: 0:文本, 1:图片
		CreateTime time.Time      `db:"create_time"` // 创建时间
		UpdateTime time.Time      `db:"update_time"` // 更新时间
		DeleteTime time.Time      `db:"delete_time"` // 删除时间
		DelState   int64          `db:"del_state"`   // 删除状态: 0-正常, 1-已删除
		Version    int64          `db:"version"`     // 版本号(乐观锁)
	}
)

func newChatMessagesModel(conn sqlx.SqlConn) *defaultChatMessagesModel {
	return &defaultChatMessagesModel{
		conn:  conn,
		table: "`chat_messages`",
	}
}

func (m *defaultChatMessagesModel) Insert(ctx context.Context, session sqlx.Session, data *ChatMessages) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	data.DelState = globalkey.DelStateNo

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, chatMessagesRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.RoomId, data.UserId, data.Content, data.MsgType, data.DeleteTime, data.DelState, data.Version)
	}
	return m.conn.ExecCtx(ctx, query, data.RoomId, data.UserId, data.Content, data.MsgType, data.DeleteTime, data.DelState, data.Version)
}

func (m *defaultChatMessagesModel) FindOne(ctx context.Context, id uint64) (*ChatMessages, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  and del_state = ? limit 1", chatMessagesRows, m.table)
	var resp ChatMessages
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, globalkey.DelStateNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChatMessagesModel) Update(ctx context.Context, session sqlx.Session, data *ChatMessages) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chatMessagesRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.RoomId, data.UserId, data.Content, data.MsgType, data.DeleteTime, data.DelState, data.Version, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.RoomId, data.UserId, data.Content, data.MsgType, data.DeleteTime, data.DelState, data.Version, data.Id)
}

func (m *defaultChatMessagesModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *ChatMessages) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, chatMessagesRowsWithPlaceHolder)
	if session != nil {
		sqlResult, err = session.ExecCtx(ctx, query, data.RoomId, data.UserId, data.Content, data.MsgType, data.DeleteTime, data.DelState, data.Version, data.Id, oldVersion)
	} else {
		sqlResult, err = m.conn.ExecCtx(ctx, query, data.RoomId, data.UserId, data.Content, data.MsgType, data.DeleteTime, data.DelState, data.Version, data.Id, oldVersion)
	}

	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultChatMessagesModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *ChatMessages) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteTime = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "ChatMessagesModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultChatMessagesModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultChatMessagesModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultChatMessagesModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ChatMessages, error) {

	builder = builder.Columns(chatMessagesRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatMessages

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatMessagesModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatMessages, error) {

	builder = builder.Columns(chatMessagesRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatMessages

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatMessagesModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ChatMessages, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(chatMessagesRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ChatMessages

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultChatMessagesModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ChatMessages, error) {

	builder = builder.Columns(chatMessagesRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatMessages

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatMessagesModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ChatMessages, error) {

	builder = builder.Columns(chatMessagesRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ChatMessages

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultChatMessagesModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultChatMessagesModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultChatMessagesModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChatMessagesModel) tableName() string {
	return m.table
}
